<%@ page contentType="text/html;charset=EUC-KR"%>
<HTML>
<HEAD>
<TITLE>전화번호부</TITLE>
</HEAD>
<FRAMESET ROWS='368,1' FRAMEBORDER='NO' BORDER='1' FRAMESPACING='0'>
	<FRAME SRC='sms.SmsServ?cmd=sms_01_010p_main' NAME='reg' SCROLLING='no'
		MARGINWIDTH='0' MARGINHEIGHT='0' FRAMEBORDER='no' NORESIZE>
	<FRAME SRC='/nara/jsp/sms/below.jsp' NAME='below' SCROLLING='no'
		MARGINWIDTH='0' MARGINHEIGHT='0' FRAMEBORDER='no' NORESIZE>
</FRAMESET>
</HTML>