CREATE TABLESPACE KP2_INDX
DATAFILE '/kebiportal/oracle/oradata/kebi/kp2_idx.dbf' SIZE 1024M
AUTOEXTEND ON NEXT 1024M;

CREATE TABLESPACE KP2_DATA
DATAFILE '/kebiportal/oracle/oradata/kebi/kp2_data.dbf' SIZE 4096M
AUTOEXTEND ON NEXT 2054M;

CREATE USER kebi IDENTIFIED BY kebi
DEFAULT TABLESPACE KP2_DATA
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, DBA TO kebi WITH ADMIN OPTION;

ALTER USER kebi DEFAULT ROLE ALL;


/** 나라비전 **/
CREATE TABLESPACE KP2_INDX
DATAFILE '/opt/oracle/oradata/kebi/kp2_idx.dbf' SIZE 1024M
AUTOEXTEND ON NEXT 1024M;

CREATE TABLESPACE KP2_DATA
DATAFILE '/opt/oracle/oradata/kebi/kp2_data.dbf' SIZE 4096M
AUTOEXTEND ON NEXT 2054M;

CREATE USER km5 IDENTIFIED BY km5
DEFAULT TABLESPACE KP2_DATA
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, DBA TO km5 WITH ADMIN OPTION;

ALTER USER km5 DEFAULT ROLE ALL;