SET DEFINE OFF;

CREATE TABLE DISK_CONFIG 
(
  DOMAIN                      VARCHAR2(100),
  DISK_USER_ENABLE_FLAG       NUMBER(1),
  DISK_USER_MAX_QUOTA         NUMBER, /* 사용자 개인용량 */
  BIGMAIL_MAX_VALIDITY_DAYS   NUMBER, /* 대용량메일 유효기간 */
  BIGMAIL_MAX_DOWNLOAD_LIMIT  NUMBER, /* 대용량메일 다운로드 횟수 */
  WEBLINK_FOLDER_ENABLE       NUMBER(1),
  GUEST_FOLDER_ENABLE         NUMBER(1),
  VIRUS_CHECK_ENABLE          NUMBER(1),
  UPLOAD_FILE_SIZE_LIMIT      NUMBER, /* 업로드 용량제한 */
  LOG_USER_VIEW_MONTHS        NUMBER, 
  LOG_PRESERVATION_MONTHS     NUMBER  /* 관리자 로그 삭제 */
);

CREATE TABLE DISK_FILE_FILTER 
(
  CONSTRAINT DISK_FILE_FILTER_PK
  PRIMARY KEY (FILTER_ID)
  USING INDEX TABLESPACE KP2_DATA,
  FILTER_ID NUMBER,
  FILTER_ITEM VARCHAR2(2000)
);

CREATE SEQUENCE SEQ_DISK_FILE_FILTER
START WITH 1 
INCREMENT BY 1;

CREATE TABLE DISK_IP_WHITELIST 
(
  CONSTRAINT DISK_IP_WHITELIST_PK
  PRIMARY KEY (WHITELIST_ID)
  USING INDEX TABLESPACE KP2_DATA,
  WHITELIST_ID NUMBER,
  WHITELIST_IP VARCHAR2(100)
);

CREATE SEQUENCE SEQ_DISK_IP_WHITELIST
START WITH 1 
INCREMENT BY 1;

CREATE TABLE DISK_IP_BLACKLIST 
(
  CONSTRAINT DISK_IP_BLACKLIST_PK
  PRIMARY KEY (BLACKLIST_ID)
  USING INDEX TABLESPACE KP2_DATA,
  BLACKLIST_ID NUMBER,
  BLACKLIST_IP VARCHAR2(100)
);

CREATE SEQUENCE SEQ_DISK_IP_BLACKLIST
START WITH 1 
INCREMENT BY 1;
 
CREATE TABLE DISK_USER
(
  CONSTRAINT DISK_USER_PK
  PRIMARY KEY (USERS_IDX)
  USING INDEX TABLESPACE KP2_DATA,
  USERS_IDX                   VARCHAR2(200),
  USERS_PASSWD                VARCHAR2(100),
  HOME_DIRECTORY              VARCHAR2(2000),
  ENABLE_FLAG                 NUMBER(1),
  READ_PERMISSION             NUMBER(1),
  WRITE_PERMISSION            NUMBER(1),
  REMOVE_PERMISSION           NUMBER(1),
  IDLE_TIME                   NUMBER,  
  UPLOAD_RATE                 NUMBER,  
  DOWNLOAD_RATE               NUMBER, 
  MAX_LOGIN_NUMBER            NUMBER, 
  MAX_LOGIN_PER_IP            NUMBER, 
  DISK_USAGE                  NUMBER, 
  DISK_QUOTA                  NUMBER,  
  BIGMAIL_VALIDITY_DAYS       NUMBER,
  BIGMAIL_DOWNLOAD_LIMIT      NUMBER,
  BIGMAIL_MAX_VALIDITY_DAYS   NUMBER,
  BIGMAIL_MAX_DOWNLOAD_LIMIT  NUMBER,
  LAST_ACCESS_IP              VARCHAR2(100),
  LAST_ACCESS_TIME            DATE
);

INSERT INTO DISK_USER (
  USERS_IDX, USERS_PASSWD, HOME_DIRECTORY, 
  ENABLE_FLAG, READ_PERMISSION, WRITE_PERMISSION, 
  REMOVE_PERMISSION, IDLE_TIME, UPLOAD_RATE, 
  DOWNLOAD_RATE, MAX_LOGIN_NUMBER, MAX_LOGIN_PER_IP, 
  DISK_USAGE, DISK_QUOTA, BIGMAIL_VALIDITY_DAYS, 
  BIGMAIL_DOWNLOAD_LIMIT, BIGMAIL_MAX_VALIDITY_DAYS, BIGMAIL_MAX_DOWNLOAD_LIMIT, 
  LAST_ACCESS_IP, LAST_ACCESS_TIME
) VALUES (
  'webmaster@arc.nara.co.kr', '12345', 'res/home/webmaster', 
  1, 1, 1, 
  1, 0, 0,
  0, 0, 0,
  0, 1073741824, 7, 
  100, 7, 100,
  '', sysdate
);
INSERT INTO DISK_USER (
  USERS_IDX, USERS_PASSWD, HOME_DIRECTORY, 
  ENABLE_FLAG, READ_PERMISSION, WRITE_PERMISSION, 
  REMOVE_PERMISSION, IDLE_TIME, UPLOAD_RATE, 
  DOWNLOAD_RATE, MAX_LOGIN_NUMBER, MAX_LOGIN_PER_IP, 
  DISK_USAGE, DISK_QUOTA, BIGMAIL_VALIDITY_DAYS, 
  BIGMAIL_DOWNLOAD_LIMIT, BIGMAIL_MAX_VALIDITY_DAYS, BIGMAIL_MAX_DOWNLOAD_LIMIT, 
  LAST_ACCESS_IP, LAST_ACCESS_TIME
) VALUES (
  'kebi@arc.nara.co.kr', '12345', 'res/home/kebi', 
  1, 1, 1, 
  1, 0, 0,
  0, 0, 0,
  0, 1073741824, 7, 
  100, 7, 100,
  '', sysdate
);
COMMIT;

CREATE TABLE DISK_GROUP
(
  CONSTRAINT DISK_GROUP_PK
  PRIMARY KEY (GROUP_IDX)
  USING INDEX TABLESPACE KP2_DATA,
  GROUP_IDX       NUMBER,
  USER_GROUP_IDX  NUMBER,
  GROUP_NAME      VARCHAR2(200),
  HOME_DIRECTORY  VARCHAR2(2000),
  ENABLE_FLAG     NUMBER(1),
  DISK_USAGE      NUMBER,
  DISK_QUOTA      NUMBER
);

CREATE SEQUENCE SEQ_DISK_GROUP
START WITH 1 
INCREMENT BY 1;

CREATE INDEX IX_DISK_GROUP_NAME 
ON DISK_GROUP (GROUP_NAME)
TABLESPACE KP2_INDX;


Insert into DISK_GROUP
   (GROUP_IDX, USER_GROUP_IDX, GROUP_NAME, HOME_DIRECTORY, ENABLE_FLAG, DISK_USAGE, DISK_QUOTA)
 Values
   (SEQ_DISK_GROUP.NEXTVAL, 0, '테스트그룹1(모든권한)', 'res/group/1', 1, 0, 1073741824);
Insert into DISK_GROUP
   (GROUP_IDX, USER_GROUP_IDX, GROUP_NAME, HOME_DIRECTORY, ENABLE_FLAG, DISK_USAGE, DISK_QUOTA)
 Values
   (SEQ_DISK_GROUP.NEXTVAL, 0, '테스트그룹2(읽기)', 'res/group/2', 1, 0, 1073741824);
Insert into DISK_GROUP
   (GROUP_IDX, USER_GROUP_IDX, GROUP_NAME, HOME_DIRECTORY, ENABLE_FLAG, DISK_USAGE, DISK_QUOTA)
 Values
   (SEQ_DISK_GROUP.NEXTVAL, 0, '테스트그룹3(쓰기)', 'res/group/3', 1, 0, 1073741824);
COMMIT;

CREATE TABLE DISK_GROUP_MEMBER
(
  GROUP_IDX          NUMBER(38),
  USERS_IDX          VARCHAR2(100),
  ENABLE_FLAG        NUMBER(1),
  READ_PERMISSION    NUMBER(1),
  WRITE_PERMISSION   NUMBER(1),
  REMOVE_PERMISSION  NUMBER(1)
);

CREATE INDEX IX_DISK_GROUP_MEMBER_GROUP_IDX 
ON DISK_GROUP_MEMBER (GROUP_IDX) 
TABLESPACE KP2_INDX;

CREATE INDEX IX_DISK_GROUP_MEMBER_USERS_IDX 
ON DISK_GROUP_MEMBER (USERS_IDX) 
TABLESPACE KP2_INDX;

Insert into DISK_GROUP_MEMBER
   (GROUP_IDX, USERS_IDX, ENABLE_FLAG, READ_PERMISSION, WRITE_PERMISSION, REMOVE_PERMISSION)
 Values
   (1, 'webmaster@arc.nara.co.kr', 1, 1, 1, 1);
Insert into DISK_GROUP_MEMBER
   (GROUP_IDX, USERS_IDX, ENABLE_FLAG, READ_PERMISSION, WRITE_PERMISSION, REMOVE_PERMISSION)
 Values
   (2, 'webmaster@arc.nara.co.kr', 1, 1, 0, 0);
Insert into DISK_GROUP_MEMBER
   (GROUP_IDX, USERS_IDX, ENABLE_FLAG, READ_PERMISSION, WRITE_PERMISSION, REMOVE_PERMISSION)
 Values
   (3, 'webmaster@arc.nara.co.kr', 1, 0, 1, 0);
COMMIT;

CREATE TABLE DISK_GUEST
(
  CONSTRAINT DISK_GUEST_PK
  PRIMARY KEY (GUEST_ID)
  USING INDEX TABLESPACE KP2_DATA,
  GUEST_ID           VARCHAR2(50),
  GUEST_PASSWORD     VARCHAR2(50),
  USERS_IDX          VARCHAR2(200),
  EMAIL_ADDRESS      VARCHAR2(200),
  HOME_DIRECTORY     VARCHAR2(2000),
  ENABLE_FLAG        NUMBER(1),
  READ_PERMISSION    NUMBER(1),
  WRITE_PERMISSION   NUMBER(1),
  REMOVE_PERMISSION  NUMBER(1),
  IDLE_TIME          NUMBER,  
  UPLOAD_RATE        NUMBER,
  DOWNLOAD_RATE      NUMBER,
  MAX_LOGIN_NUMBER   NUMBER,
  MAX_LOGIN_PER_IP   NUMBER,
  EXPIRY_DATE        DATE,
  LOGIN_COUNT        NUMBER,
  LAST_ACCESS_IP     VARCHAR2(100),
  LAST_ACCESS_TIME   DATE
);

CREATE INDEX IX_DISK_GUEST_USERS_IDX 
ON DISK_GUEST (USERS_IDX) 
TABLESPACE KP2_INDX;

CREATE TABLE DISK_BIGMAIL
(
  CONSTRAINT DISK_BIGMAIL_PK
  PRIMARY KEY (FILE_ID)
  USING INDEX TABLESPACE KP2_DATA,
  FILE_ID         VARCHAR2(50),
  USERS_IDX       VARCHAR2(200),
  FILE_NAME       VARCHAR2(1000),
  FILE_SIZE       NUMBER,
  DOWNLOAD_COUNT  NUMBER,
  DOWNLOAD_LIMIT  NUMBER,
  UPLOAD_DATE     DATE,
  EXPIRY_DATE     DATE
);

CREATE INDEX IX_DISK_BIGMAIL_USERS_IDX 
ON DISK_BIGMAIL (USERS_IDX)
TABLESPACE KP2_INDX;

CREATE TABLE DISK_STATISTICS
(
  CONSTRAINT DISK_STATISTICS_PK
  PRIMARY KEY (DATE_HOUR)
  USING INDEX TABLESPACE KP2_DATA,
  DATE_HOUR        DATE,
  UPLOAD_COUNT     NUMBER DEFAULT 0,
  UPLOAD_AMOUNT    NUMBER DEFAULT 0,
  DOWNLOAD_COUNT   NUMBER DEFAULT 0,
  DOWNLOAD_AMOUNT  NUMBER DEFAULT 0,
  DELETE_COUNT     NUMBER DEFAULT 0,
  DELETE_AMOUNT    NUMBER DEFAULT 0
);