------ 신규 생성 테이블
------ACCOUNT_CHANGE
------A_KEPETROORKR
------A_KEPETROORKR_CONTENT
------BATCH_LOG
------BLOCK_MAIL_INFO
------LINKAGE_GRANTIP
------LOGIN_LOG
------MANAGER_GRANTIP
------MEMO
------M_KEPETROORKR_CONTENT
------M_TAG_BASE
------M_TAG_KEPETROORKR
------NOTE_ATTACHE
------NOTE_KEPETROORKR
------NOTE_RECONF
------POPUP
------REL_NOTE_ATTACHE
------TEMP_DATE_VAL
------USERS_PASSWD_CHANGE
------USERS_PAUSE
------USERS_RECENT_ADDRESS
------USERS_SIGNATURE
------USER_DUTY
------USER_GROUP2
------USER_GROUP3
------USER_GROUP_LIST2
------USER_GROUP_LIST3
--------------------------------------------------------------------------

-- TABLE [ACCOUNT_CHANGE]
DROP TABLE ACCOUNT_CHANGE;
CREATE TABLE ACCOUNT_CHANGE
   (
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      DOMAIN VARCHAR2 (100) NOT NULL ,
      REQ_ID VARCHAR2 (100) NOT NULL ,
      REQ_PASSWD VARCHAR2 (100) NOT NULL ,
      REQ_DATE DATE NOT NULL ,
      CONFIRM_USERS_IDX VARCHAR2 (200) ,
      CONFIRM_DATE DATE ,
      STATUS CHAR (1) ,
      CONSTRAINT PK_ACCOUNT_CHANGE PRIMARY KEY (USERS_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE A_KEPETROORKR;
CREATE TABLE A_KEPETROORKR
(
    M_IDX NUMBER NOT NULL ,
    M_ORD NUMBER DEFAULT 0 NOT NULL ,
    MBOX_IDX NUMBER NOT NULL ,
    USERS_IDX VARCHAR2 (200) NOT NULL ,
    M_TAG CHAR (1) ,
    M_SENDER VARCHAR2 (200) ,
    M_SENDERNM VARCHAR2 (100) ,
    M_TO VARCHAR2 (4000) ,
    M_CC VARCHAR2 (4000) ,
    M_BCC VARCHAR2 (4000) ,
    M_RETURN VARCHAR2 (200) ,
    M_TYPE VARCHAR2 (50) ,
    M_CHARSET VARCHAR2 (50) ,
    M_TITLE VARCHAR2 (255) ,
    M_CONTENT CLOB ,
    M_TIME DATE ,
    M_SIZE NUMBER ,
    M_ATTACHE VARCHAR2 (50) ,
    M_ATTNUM VARCHAR2 (1000) ,
    M_ATTNAME VARCHAR2 (4000) ,
    M_ATTSIZE VARCHAR2 (4000) ,
    M_ATTTYPE VARCHAR2 (4000) ,
    M_ISREAD CHAR (1) ,
    M_PRIORITY NUMBER (1) ,
    M_INJURIOUSE CHAR (1) ,
    M_FILENAME VARCHAR2 (70) ,
    M_FILEPATH VARCHAR2 (4000) ,
    M_DELETED CHAR (1) DEFAULT 'N' ,
    M_REMOTEIP VARCHAR2 (20),
    M_SECURE_YN CHAR(1) default 'N',
    CONSTRAINT     PK_A_KEPETROORKR PRIMARY KEY (M_IDX, M_ORD) USING INDEX TABLESPACE KP2_INDX
)
PCTFREE 20
PCTUSED 60
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 100M
    NEXT 100M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)

TABLESPACE KP2_DATA LOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL;


CREATE INDEX IDX_A_KEPETROORKR_01
ON A_KEPETROORKR
(
    MBOX_IDX ASC,
    M_TIME ASC
)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 20M
    NEXT 20M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_INDX NOCOMPRESS NOPARALLEL;

CREATE INDEX IDX_A_KEPETROORKR_02
ON A_KEPETROORKR
(
    USERS_IDX ASC,
    M_ISREAD ASC,
    M_TIME ASC
)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 20M
    NEXT 20M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_INDX NOCOMPRESS NOPARALLEL; 

DROP SEQUENCE SEQ_A_KEPETROORKR;
CREATE SEQUENCE SEQ_A_KEPETROORKR;

DROP TABLE A_KEPETROORKR_CONTENT;
CREATE TABLE A_KEPETROORKR_CONTENT
(
    M_IDX NUMBER NOT NULL ,
    M_ORDER NUMBER NOT NULL ,
    M_CONTENT NCLOB ,
    M_CONTENT_TYPE VARCHAR2(400),
    CONSTRAINT PK_A_KEPETROORKR_CONTENT PRIMARY KEY (M_IDX, M_ORDER ) USING INDEX TABLESPACE KP2_INDX
)
PCTFREE 20
PCTUSED 60
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 100M
    NEXT 100M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
TABLESPACE KP2_DATA LOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL;

DROP TABLE BATCH_LOG CASCADE CONSTRAINTS;
CREATE TABLE BATCH_LOG (
  BATCH_LOG_IDX    NUMBER             NOT NULL, 
  BATCH_LOG_MSG    VARCHAR2(10)       NULL, 
  BATCH_LOG_SDATE  DATE               NULL, 
  BATCH_LOG_EDATE  DATE               NULL
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

ALTER TABLE BATCH_LOG ADD
(
    CONSTRAINT PK_BATCH_LOG
    PRIMARY KEY ( BATCH_LOG_IDX )
        USING INDEX
        TABLESPACE KP2_INDX 
);

DROP SEQUENCE SEQ_BATCH_LOG;
CREATE SEQUENCE SEQ_BATCH_LOG;

DROP TABLE BLOCK_MAIL_INFO;
CREATE TABLE BLOCK_MAIL_INFO
   (
      M_IDX NUMBER ,
      MAIL_FROM VARCHAR2(4000 ),
      RCPT_TO VARCHAR2 (4000),
      FORWORD_YN CHAR (1) DEFAULT 'N' ,
      FORWORD_DATE DATE,
      CONSTRAINT PK_BLOCK_MAIL_INFO PRIMARY KEY (M_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE LINKAGE_GRANTIP CASCADE CONSTRAINTS ;

CREATE TABLE LINKAGE_GRANTIP
(
  GRANT_IP_IDX  NUMBER(2)                       NOT NULL,
  GRANT_IP      VARCHAR2(15 BYTE)               NOT NULL,
  USERS_IDX     VARCHAR2(200 BYTE),
  INSERT_DATE   DATE,
  UPDATE_DATE   DATE
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;


ALTER TABLE LINKAGE_GRANTIP ADD (
  CONSTRAINT PK_LINKAGE_GRANTIP
 PRIMARY KEY
 (GRANT_IP_IDX)
    USING INDEX 
    TABLESPACE KP2_INDX
); 

DROP TABLE LOGIN_LOG;
CREATE TABLE LOGIN_LOG
   (
      LOGIN_LOG_IDX NUMBER NOT NULL ,
      CONNECT_IDX VARCHAR2 (40) NOT NULL ,
      CONNECT_ID VARCHAR2 (20) NOT NULL ,
      DOMAIN VARCHAR2 (20) NOT NULL ,
      CONNECT_IP VARCHAR2 (15) NOT NULL ,
      CONNECT_TIME DATE NOT NULL ,
      LOGIN_YN CHAR (1) ,
      CERTIY_YN CHAR (1) ,
      ERROR_CODE VARCHAR2 (20) ,
      DESCRIPTION VARCHAR2 (1000) ,
      CONSTRAINT PK_LOGIN_LOG PRIMARY KEY (LOGIN_LOG_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

CREATE INDEX IDX_LOGIN_LOG_01
   ON LOGIN_LOG 
   (
      CONNECT_IDX ASC 
   )
TABLESPACE KP2_INDX NOLOGGING; 

CREATE INDEX IDX_LOGIN_LOG_02
   ON LOGIN_LOG 
   (
      CONNECT_ID ASC 
   )
TABLESPACE KP2_INDX NOLOGGING;

CREATE INDEX IDX_LOGIN_LOG_03
   ON LOGIN_LOG 
   (
      CONNECT_IP ASC 
   )
TABLESPACE KP2_INDX NOLOGGING;

CREATE INDEX IDX_LOGIN_LOG_04
   ON LOGIN_LOG 
   (
      CONNECT_TIME ASC 
   )
TABLESPACE KP2_INDX NOLOGGING;

CREATE INDEX IDX_LOGIN_LOG_05
   ON LOGIN_LOG 
   (
      LOGIN_YN ASC 
   )
TABLESPACE KP2_INDX NOLOGGING;

DROP SEQUENCE SEQ_LOGIN_LOG;
CREATE SEQUENCE SEQ_LOGIN_LOG;

DROP TABLE MANAGER_GRANTIP;
CREATE TABLE MANAGER_GRANTIP
   (
      GRANT_IP_IDX NUMBER (2) NOT NULL ,
      GRANT_IP VARCHAR2 (15) NOT NULL ,
      USERS_IDX VARCHAR2 (200) ,
      INSERT_DATE DATE ,
      UPDATE_DATE DATE ,
      CONSTRAINT PK_MANAGER_GRANTIP PRIMARY KEY (GRANT_IP_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE MEMO;
CREATE TABLE MEMO
   (
      USERS_IDX VARCHAR2 (25) NOT NULL ,
      MEMO_IDX NUMBER NOT NULL ,
      MEMO_COLOR VARCHAR2 (20) NOT NULL ,
      MEMO_CONTENT VARCHAR2 (2000) NOT NULL ,
      DIPLAY_YN CHAR (1) NOT NULL ,
      CREATE_DATE DATE ,
      UPDATE_DATE DATE ,
      CONSTRAINT PK_MEMO PRIMARY KEY (MEMO_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP SEQUENCE SEQ_MEMO;
CREATE SEQUENCE SEQ_MEMO;

DROP TABLE M_KEPETROORKR_CONTENT;
CREATE TABLE M_KEPETROORKR_CONTENT
(
    M_IDX NUMBER NOT NULL ,
    M_ORDER NUMBER NOT NULL ,
    M_CONTENT NCLOB ,
    M_CONTENT_TYPE VARCHAR2(400),
    CONSTRAINT PK_M_KEPETROORKR_CONTENT PRIMARY KEY (M_IDX, M_ORDER ) USING INDEX TABLESPACE KP2_INDX
)
PCTFREE 20
PCTUSED 60
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 100M
    NEXT 100M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
TABLESPACE KP2_DATA LOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL;

DROP TABLE M_TAG_BASE;
CREATE TABLE M_TAG_BASE
   (
      TAG_TYPE NUMBER (3) NOT NULL ,
      TAG_NAME VARCHAR2 (200) ,
      TAG_IMG_NAME VARCHAR2 (100) NOT NULL ,
      TAG_ORD NUMBER (3) 
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE M_TAG_KEPETROORKR;
CREATE TABLE M_TAG_KEPETROORKR
(
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      TAG_TYPE NUMBER (3) NOT NULL ,
      TAG_NAME VARCHAR2 (200) ,
      TAG_IMG_NAME VARCHAR2 (100) NOT NULL ,
      TAG_ORD NUMBER (3) NOT NULL ,
      CONSTRAINT PK_M_TAG_KEPETROORKR PRIMARY KEY (USERS_IDX ,TAG_ORD ) USING INDEX TABLESPACE KP2_INDX          
)
PCTFREE 20
PCTUSED 60
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 50M
    NEXT 50M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_DATA NOCOMPRESS NOPARALLEL;

CREATE INDEX IDX_M_TAG_KEPETROORKR_01
ON M_TAG_KEPETROORKR
(
    USERS_IDX ASC,
    TAG_TYPE ASC
)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 20M
    NEXT 20M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_INDX NOCOMPRESS NOPARALLEL;

DROP TABLE NOTE_ATTACHE;
CREATE TABLE NOTE_ATTACHE
   (
      NOTE_ATTACHE_IDX NUMBER NOT NULL ,
      NOTE_ATTACHE_LOCATION VARCHAR2 (200) NOT NULL ,
      NOTE_ATTACHE_LOGICAL_NM VARCHAR2 (100) NOT NULL ,
      NOTE_ATTACHE_PHYSICAL_NM VARCHAR2 (100) NOT NULL ,
      NOTE_ATTACHE_SIZE NUMBER ,
      CONSTRAINT PK_NOTE_ATTACHE PRIMARY KEY (NOTE_ATTACHE_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE NOTE_KEPETROORKR;
CREATE TABLE NOTE_KEPETROORKR
(
      NOTE_IDX NUMBER NOT NULL ,
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      USERS_ID VARCHAR2 (200) NOT NULL ,
      DOMAIN VARCHAR2 (200) NOT NULL ,
      NOTE_BOX_TYPE NUMBER (1) NOT NULL ,
      NOTE_SAVE_YN CHAR (1) DEFAULT 'N' NOT NULL ,
      NOTE_FROM VARCHAR2 (2000) ,
      NOTE_TO VARCHAR2 (2000) ,
      NOTE_TITLE VARCHAR2(500),
      NOTE_CONTENT NCLOB ,
      NOTE_TIME DATE ,
      REF_NOTE_IDX NUMBER ,
      NOTE_ISREAD CHAR (1) DEFAULT 'N' NOT NULL ,
      CONSTRAINT PK_NOTE_KEPETROORKR PRIMARY KEY (NOTE_IDX ) USING INDEX TABLESPACE KP2_INDX
)
PCTFREE 10
PCTUSED 80
INITRANS 1
MAXTRANS 255
STORAGE
(
    INITIAL 5M
    NEXT 5M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
TABLESPACE KP2_DATA LOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL; 

DROP SEQUENCE SEQ_NOTE_KEPETROORKR;    
CREATE SEQUENCE SEQ_NOTE_KEPETROORKR;

DROP TABLE NOTE_RECONF;
CREATE TABLE NOTE_RECONF
   (
      NOTE_RECONF_IDX NUMBER NOT NULL ,
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      NOTE_IDX NUMBER NOT NULL ,
      NOTE_RECONF_TO VARCHAR2 (200) ,
      NOTE_RECONF_TO_ORI VARCHAR2 (200) ,
      NOTE_SEND_TIME DATE ,
      NOTE_READ_TIME DATE ,
      NOTE_SEND_IDX NUMBER ,
      NOTE_RECONF_STATE NUMBER (1) ,
      CONSTRAINT PK_NOTE_RECONF PRIMARY KEY (NOTE_RECONF_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;
CREATE INDEX IDX_NOTE_RECONF_1 ON NOTE_RECONF (USERS_IDX) TABLESPACE KP2_INDX NOLOGGING ; 

DROP SEQUENCE SEQ_NOTE_RECONF;
CREATE SEQUENCE SEQ_NOTE_RECONF;

DROP TABLE POPUP;
CREATE TABLE POPUP
(
  POPUP_IDX      NUMBER(10),
  POPUP_URL      VARCHAR2(256 BYTE),
  POPUP_STATE    CHAR(1 BYTE)                   DEFAULT 'S',
  POPUP_START    VARCHAR2(10 BYTE),
  POPUP_END      VARCHAR2(10 BYTE),
  POPUP_TOP      NUMBER(4),
  POPUP_WIDTH    NUMBER(4),
  POPUP_HEIGHT   NUMBER(4),
  POPUP_TYPE     CHAR(1 BYTE)                   DEFAULT 'F',
  POPUP_TITLE    VARCHAR2(128 BYTE),
  POPUP_LEFT     NUMBER(4),
  POPUP_CONTENT  NCLOB
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

COMMENT ON COLUMN POPUP.POPUP_TYPE IS 'F , B' ;

DROP SEQUENCE SEQ_POPUP;
CREATE SEQUENCE SEQ_POPUP;

DROP TABLE REL_NOTE_ATTACHE;
CREATE TABLE REL_NOTE_ATTACHE
   (
      NOTE_IDX NUMBER ,
      NOTE_ATTACHE_IDX NUMBER 
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

CREATE INDEX IDX_REL_NOTE_ATTACHE1
   ON REL_NOTE_ATTACHE 
   (
      NOTE_IDX ASC 
   )
TABLESPACE KP2_INDX NOLOGGING NOCOMPRESS NOPARALLEL ;

CREATE INDEX IDX_REL_NOTE_ATTACHE2
   ON REL_NOTE_ATTACHE 
   (
      NOTE_ATTACHE_IDX ASC 
   )
TABLESPACE KP2_INDX  NOLOGGING NOCOMPRESS NOPARALLEL ;

drop table TEMP_DATE_VAL CASCADE CONSTRAINTS;
CREATE TABLE TEMP_DATE_VAL
(DATE_TYPE varchar2(4),
 DATE_VALUE VARCHAR2(10),
 DATE_NAME  VARCHAR2(10));

DROP TABLE USERS_PASSWD_CHANGE;
CREATE TABLE USERS_PASSWD_CHANGE
    (
        USERS_PASSWD_CHANGE_IDX NUMBER,
        USERS_IDX VARCHAR2(400) NOT NULL,
        BEFORE_PASSWD VARCHAR2(400) NOT NULL,
        AFTER_PASSWD VARCHAR2(400) NOT NULL,
        CONNECT_IP VARCHAR2(15),
        CHANGE_DATE DATE NOT NULL,
        CONSTRAINT PK_USERS_PASSWD_CHANGE PRIMARY KEY (USERS_PASSWD_CHANGE_IDX) USING INDEX TABLESPACE KP2_INDX
    )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

CREATE INDEX IDX_USERS_PASSWD_CHANGE_1 ON USERS_PASSWD_CHANGE(USERS_IDX) 
TABLESPACE KP2_INDX NOLOGGING;


DROP SEQUENCE SEQ_USERS_PASSWD_CHANGE;
CREATE SEQUENCE SEQ_USERS_PASSWD_CHANGE;

DROP TABLE USERS_KEYS;
CREATE TABLE USERS_KEYS
   (
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      CNS VARCHAR2 (128) NOT NULL ,
      OUS VARCHAR2 (128) ,
      OS VARCHAR2 (128) ,
      CS VARCHAR2 (128) ,
      SERIALKEY VARCHAR2 (128) NOT NULL ,
      TYPE CHAR (1) DEFAULT 'G' ,
      DATETO VARCHAR2 (24) ,
      DATEFROM VARCHAR2 (24) ,
      CONSTRAINT PK_USERS_KEYS PRIMARY KEY (USERS_IDX ,SERIALKEY ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE USERS_PAUSE;
CREATE TABLE USERS_PAUSE
   (
      USERS_PAUSE_IDX NUMBER (10) NOT NULL ,
      DOMAIN VARCHAR2 (100) NOT NULL ,
      USERS_PAUSE_ID VARCHAR2 (100) ,
      USERS_PAUSE_NAME VARCHAR2 (200) ,
      USERS_PAUSE_PASSWD VARCHAR2 (50) ,
      USERS_PAUSE_JUMIN1 VARCHAR2 (6) ,
      USERS_PAUSE_JUMIN2 VARCHAR2 (7) ,
      USERS_PAUSE_DEPARTMENT VARCHAR2 (100) ,
      USERS_PAUSE_LICENCENUM VARCHAR2 (200) ,
      CONSTRAINT PK_USERS_PAUSE PRIMARY KEY (USERS_PAUSE_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP SEQUENCE SEQ_USERS_PAUSE;
CREATE SEQUENCE SEQ_USERS_PAUSE;

DROP TABLE USERS_RECENT_ADDRESS;
CREATE TABLE USERS_RECENT_ADDRESS
   (
      RECENT_ADDRESS_IDX NUMBER NOT NULL ,
      USERS_IDX VARCHAR2 (200) NOT NULL ,
      ORD_IDX NUMBER ,
      ADDRESS_NAME VARCHAR2 (200) ,
      ADDRESS_EMAIL VARCHAR2 (200) NOT NULL ,
      USING_DT DATE DEFAULT SYSDATE ,
      CONSTRAINT PK_USERS_RECENT_ADDRESS PRIMARY KEY (RECENT_ADDRESS_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA LOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;
CREATE INDEX  IDX_USERS_RECENT_ADDRESS_01 ON USERS_RECENT_ADDRESS (USERS_IDX)
TABLESPACE KP2_INDX NOLOGGING NOCOMPRESS NOPARALLEL ;

DROP SEQUENCE SEQ_USERS_RECENT_ADDRESS;
CREATE SEQUENCE SEQ_USERS_RECENT_ADDRESS ;

DROP TABLE USERS_SIGNATURE CASCADE CONSTRAINTS;
CREATE TABLE USERS_SIGNATURE
(
  SIGN_IDX    NUMBER       NOT NULL,
  USERS_IDX   VARCHAR2(200) NOT NULL,
  SIGN_TITLE  VARCHAR2(4000),
  SIGN_DEFAULT NUMBER(1) DEFAULT 0,
  SIGN_STMT   VARCHAR2(4000)
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;
drop sequence SEQ_USERS_SIGNATURE;
create sequence SEQ_USERS_SIGNATURE;

ALTER TABLE USERS_SIGNATURE ADD CONSTRAINT PK_USERS_SIGNATURE PRIMARY KEY (SIGN_IDX)
USING INDEX  TABLESPACE KP2_INDX;               

CREATE INDEX  IDX_SIGNATURE_01 ON USERS_SIGNATURE (USERS_IDX)
TABLESPACE KP2_INDX;

DROP TABLE USER_DUTY;
CREATE TABLE USER_DUTY
   (
      DUTY CHAR (18) NOT NULL ,
      DUTY_SORT_NO CHAR (18) ,
      CONSTRAINT PK_USER_DUTY PRIMARY KEY (DUTY ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE USER_GROUP2 CASCADE CONSTRAINTS;
CREATE TABLE USER_GROUP2 (
  USER_GROUP_IDX          NUMBER(9)         NOT NULL, 
  P_USER_GROUP_IDX        NUMBER(9)             NULL, 
  USER_GROUP_NAME         VARCHAR2(200)         NULL, 
  USER_GROUP_SORT_NO      NUMBER                NULL, 
  DOMAIN                  VARCHAR2(100)         NULL, 
  USER_GROUP_DEFAULT      NCHAR(32)             NULL, 
  USER_GROUP_FUNCTION     VARCHAR2(20)          NULL, 
  USER_GROUP_VOLUME       NCHAR(288)            NULL, 
  USER_GROUP_MAIL         NCHAR(32)             NULL, 
  USER_GROUP_SCHEDULE     NUMBER(1)             NULL, 
  USER_GROUP_STRUCTURE    NUMBER(1)             NULL, 
  USER_GROUP_SMS_QUOTA    NUMBER            NOT NULL, 
  USER_GROUP_ADDRESS      NUMBER(1)             NULL, 
  USER_GROUP_CODE         VARCHAR2(50)          NULL, 
  USER_GROUP_TOPCODE      VARCHAR2(50)          NULL
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

ALTER TABLE USER_GROUP2 ADD
(
    CONSTRAINT PK_USER_GROUP2
    PRIMARY KEY ( USER_GROUP_IDX )
        USING INDEX
        TABLESPACE KP2_INDX 
);

DROP TABLE USER_GROUP3 CASCADE CONSTRAINTS;
CREATE TABLE USER_GROUP3 (
  USER_GROUP_IDX          NUMBER(9)         NOT NULL, 
  P_USER_GROUP_IDX        NUMBER(9)             NULL, 
  USER_GROUP_NAME         VARCHAR2(200)         NULL, 
  USER_GROUP_SORT_NO      NUMBER                NULL, 
  DOMAIN                  VARCHAR2(100)         NULL, 
  USER_GROUP_DEFAULT      NCHAR(32)             NULL, 
  USER_GROUP_FUNCTION     VARCHAR2(20)          NULL, 
  USER_GROUP_VOLUME       NCHAR(288)            NULL, 
  USER_GROUP_MAIL         NCHAR(32)             NULL, 
  USER_GROUP_SCHEDULE     NUMBER(1)             NULL, 
  USER_GROUP_STRUCTURE    NUMBER(1)             NULL, 
  USER_GROUP_SMS_QUOTA    NUMBER            NOT NULL, 
  USER_GROUP_ADDRESS      NUMBER(1)             NULL, 
  USER_GROUP_CODE         VARCHAR2(50)          NULL, 
  USER_GROUP_TOPCODE      VARCHAR2(50)          NULL
)
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;


ALTER TABLE USER_GROUP3 ADD
(
    CONSTRAINT PK_USER_GROUP3
    PRIMARY KEY ( USER_GROUP_IDX )
        USING INDEX
        TABLESPACE KP2_INDX 
);

DROP TABLE USER_GROUP_LIST2;
CREATE TABLE USER_GROUP_LIST2
   (
      USER_GROUP_LIST_IDX NUMBER NOT NULL ,
      USERS_IDX VARCHAR2 (200) ,
      USER_GROUP_SORT_NO NUMBER ,
      DOMAIN VARCHAR2 (100) ,
      USER_GROUP_IDX NUMBER (9) NOT NULL ,
      DUTY VARCHAR2 (200) ,
      CONSTRAINT PK_USER_GROUP_LIST2 PRIMARY KEY (USER_GROUP_LIST_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

DROP TABLE USER_GROUP_LIST3;
CREATE TABLE USER_GROUP_LIST3
   (
      USER_GROUP_LIST_IDX NUMBER NOT NULL ,
      USERS_IDX VARCHAR2 (200) ,
      USER_GROUP_SORT_NO NUMBER ,
      DOMAIN VARCHAR2 (100) ,
      USER_GROUP_IDX NUMBER (9) NOT NULL ,
      DUTY VARCHAR2 (200) ,
      CONSTRAINT PK_USER_GROUP_LIST3 PRIMARY KEY (USER_GROUP_LIST_IDX ) USING INDEX TABLESPACE KP2_INDX
   )
TABLESPACE KP2_DATA NOLOGGING NOCACHE NOROWDEPENDENCIES NOMONITORING NOPARALLEL ;

------ 기존 테이블 칼럼 Modify
--select AA.COLUMN_NAME, AA.DATA_TYPE, AA.DATA_LENGTH, BB.DATA_TYPE, BB.DATA_LENGTH, AA.NULLABLE, BB.NULLABLE
--from LKY_COLUMNS AA LEFT JOIN DBA_TAB_COLUMNS BB ON AA.TABLE_NAME = BB.TABLE_NAME AND AA.COLUMN_NAME = BB.COLUMN_NAME AND BB.OWNER = 'KM5'
--WHERE AA.TABLE_NAME = 'USER_GROUP_LIST';
----------------------------------------------------------------------------------------
--[B_NARAVISIOINNET]
UPDATE B_KEPETROORKR
SET B_NOTICE_WAY = NULL;
COMMIT;
ALTER TABLE B_KEPETROORKR
MODIFY (
B_NOTICE_WAY NUMBER,
B_ATTACHE VARCHAR2(1000)
);

ALTER TABLE B_KEPETROORKR
ADD (
B_NOTICE_YN    CHAR(1),
CUSTOM_TITLE    VARCHAR2(500),
RECEIVE_USERS_IDX    VARCHAR2(200),
RECEIVE_USERS_NAME    VARCHAR2(50),
B_NOTICE_TYPE    CHAR(1)
);

--[DOMAIN]
ALTER TABLE DOMAIN ADD ( DOMAIN_PWD_LOCK_COUNT NUMBER DEFAULT 0);
ALTER TABLE DOMAIN ADD ( DOMAIN_BIGMAIL_QUOTA NUMBER DEFAULT 0);

--[MAIL_RECONF]
ALTER TABLE MAIL_RECONF
ADD (
M_IDX    NUMBER,
MAIL_RECONF_SEND    CHAR(1),
MAIL_RECONF_SEND_DATE    VARCHAR2(20)
)

--[MBOX]
ALTER TABLE MBOX
ADD (
    MBOX_PASSWD    VARCHAR2(1000),
    MBOX_PUBLIC    CHAR(1) DEFAULT 'P'
);

--[M_KEPETROORKR]
ALTER TABLE M_KEPETROORKR
MODIFY (
M_SENDER    VARCHAR2(4000),
M_RETURN    VARCHAR2(4000),
M_SENDERNM    VARCHAR2(4000),
M_TYPE    VARCHAR2(100),
M_TITLE    VARCHAR2(4000), 
M_ATTACHE    VARCHAR2(100),
M_FILENAME    VARCHAR2(1000)  
);


ALTER TABLE M_KEPETROORKR
ADD (
TAG_TYPE    NUMBER DEFAULT 0 NOT NULL,
M_ATTACH_NAME    NCLOB,
M_NOTICE    CHAR(1),
MAIL_RECONF_MESSAGE_ID    VARCHAR2(400),
M_ATTACH_SIZE    VARCHAR2(4000),
M_SECURE_YN    CHAR(1),
M_ATTACH_TYPE    VARCHAR2(4000),
M_GROUP    NUMBER,
M_ISPARSED    CHAR(1),
M_ORDER    NUMBER DEFAULT 0 NOT NULL,
M_FILEPATH    VARCHAR2(4000),
M_ATTACH_NUM    VARCHAR2(4000),
M_KIND    CHAR(1)
);

--[POP]
ALTER TABLE POP
ADD (
POP_ICON    CHAR(1),
POP_NAME    VARCHAR2(50)
);

--[PUBLICADDRESS]
ALTER TABLE PUBLICADDRESS
ADD (
PUBLICADDRESS_SORT_NO    NUMBER DEFAULT 0
);

--[PUBLICGROUP]
ALTER TABLE PUBLICGROUP
ADD (
PUBLICGROUP_SORT_NO    NUMBER DEFAULT 0
);

--[SCHEDULE]
ALTER TABLE SCHEDULE
ADD (
P_SCHEDULE_IDX    NUMBER,
USER_GROUP_IDX    NUMBER,
SCHEDULE_ALAM    NUMBER,
SHARE_GROUP_IDX    VARCHAR2(200),
SCHEDULE_ALAM_DATE    DATE,
SCHEDULE_ALAM_WAY    NUMBER
)

--[USERS]
ALTER TABLE USERS
MODIFY (
USERS_HOMEDIR    VARCHAR2(500) NOT NULL,
USERS_NAME    VARCHAR2(50) NOT NULL,
USERS_JUMIN1    VARCHAR2(200),
USERS_JUMIN2    VARCHAR2(200),
USERS_CELLNO    VARCHAR2(200),
USERS_FAXNO    VARCHAR2(200),
USERS_TELNO    VARCHAR2(200),
USERS_ZIPCODE    VARCHAR2(200),
USERS_ADDRESS1    VARCHAR2(500),
USERS_ADDRESS2    VARCHAR2(500),
USERS_COMPNAME    VARCHAR2(200),
USERS_DEPARTMENT    VARCHAR2(500)
);

ALTER TABLE USERS
ADD (
USERS_ACCOUNT_CHANGE_DATE    DATE,
USERS_DELEGATE    CHAR(1),
MAX_BIG_UPLOAD_SIZE    NUMBER,
USERS_AUTORE_LIST    VARCHAR2(1000),
USERS_MAIL_BLOCKING_AUTH    CHAR(1),
USERS_BOARD_AUTH    CHAR(1),
USERS_LOGIN_MODE    VARCHAR2(5),
USERS_USETAG    CHAR(1),
USERS_DELEGATE_LIST    VARCHAR2(4000),
USERS_OPT_AUTORE    CHAR(1),
USERS_INFO_OPEN_AGREEMENT    CHAR(1),
USERS_USE_MAIL_PREVIEW    CHAR(1),
USERS_PWD_FAIL_COUNT    NUMBER,
USERS_FWD_AUTH    CHAR(1),
USERS_MENTO_YN    CHAR(1),
USERS_PWD_FAIL_DATE    DATE,
USERS_PWD_LOCKED    CHAR(1),
USERS_MSG_YN    CHAR(1),
USERS_SMS_MAX_QUOTA DEFAULT 0
);

--[USER_GROUP]
ALTER TABLE USER_GROUP
ADD (
P_USER_GROUP_IDX    NUMBER,
USER_GROUP_SORT_NO    NUMBER
);

--[USER_GROUP_LIST]
ALTER TABLE USER_GROUP_LIST
ADD (
USER_GROUP_SORT_NO    NUMBER
);


INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  0, '선택해제', 'ico_tag00.gif', 20 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  1, '', 'ico_tag01.gif', 01 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  2, '', 'ico_tag02.gif', 02 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  3, '', 'ico_tag03.gif', 03 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  4, '', 'ico_tag04.gif', 04 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  5, '', 'ico_tag05.gif', 05 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  6, '', 'ico_tag06.gif', 06 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  7, '', 'ico_tag07.gif', 07 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  8, '', 'ico_tag08.gif', 08 );

INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES(  9, '', 'ico_tag09.gif', 09 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 10, '', 'ico_tag10.gif', 10 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 11, '', 'ico_tag11.gif', 11 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 12, '', 'ico_tag12.gif', 12 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 13, '', 'ico_tag13.gif', 13 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 14, '', 'ico_tag14.gif', 14 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 15, '', 'ico_tag15.gif', 15 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 16, '', 'ico_tag16.gif', 16 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 17, '', 'ico_tag17.gif', 17 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 18, '', 'ico_tag18.gif', 18 );
INSERT INTO M_TAG_BASE (TAG_TYPE, TAG_NAME, TAG_IMG_NAME, TAG_ORD) VALUES( 19, '', 'ico_tag19.gif', 19 );
COMMIT;

insert into temp_date_val values('HH24', '01', '01시'); 
insert into temp_date_val values('HH24', '02', '02시');
insert into temp_date_val values('HH24', '03', '03시');
insert into temp_date_val values('HH24', '04', '04시');
insert into temp_date_val values('HH24', '05', '05시');
insert into temp_date_val values('HH24', '06', '06시');
insert into temp_date_val values('HH24', '07', '07시');
insert into temp_date_val values('HH24', '08', '08시');
insert into temp_date_val values('HH24', '09', '09시');
insert into temp_date_val values('HH24', '10', '10시');
insert into temp_date_val values('HH24', '11', '11시');
insert into temp_date_val values('HH24', '12', '12시');
insert into temp_date_val values('HH24', '13', '13시');
insert into temp_date_val values('HH24', '14', '14시');
insert into temp_date_val values('HH24', '15', '15시');
insert into temp_date_val values('HH24', '16', '16시');
insert into temp_date_val values('HH24', '17', '17시');
insert into temp_date_val values('HH24', '18', '18시');
insert into temp_date_val values('HH24', '19', '19시');
insert into temp_date_val values('HH24', '20', '20시');
insert into temp_date_val values('HH24', '21', '21시');
insert into temp_date_val values('HH24', '22', '22시');
insert into temp_date_val values('HH24', '23', '23시');
insert into temp_date_val values('HH24', '24', '24시');


insert into temp_date_val values('D', '1', '월요일');
insert into temp_date_val values('D', '2', '화요일');
insert into temp_date_val values('D', '3', '수요일');
insert into temp_date_val values('D', '4', '목요일');
insert into temp_date_val values('D', '5', '금요일');
insert into temp_date_val values('D', '6', '토요일');
insert into temp_date_val values('D', '7', '일요일');

insert into temp_date_val values('W', '1', '1주');
insert into temp_date_val values('W', '2', '2주');
insert into temp_date_val values('W', '3', '3주');
insert into temp_date_val values('W', '4', '4주');
insert into temp_date_val values('W', '5', '5주');

insert into temp_date_val values('MM', '01', '1월');
insert into temp_date_val values('MM', '02', '2월');
insert into temp_date_val values('MM', '03', '3월');
insert into temp_date_val values('MM', '04', '4월');
insert into temp_date_val values('MM', '05', '5월');
insert into temp_date_val values('MM', '06', '6월');
insert into temp_date_val values('MM', '07', '7월');
insert into temp_date_val values('MM', '08', '8월');
insert into temp_date_val values('MM', '09', '9월');
insert into temp_date_val values('MM', '10', '10월');
insert into temp_date_val values('MM', '11', '11월');
insert into temp_date_val values('MM', '12', '12월');
COMMIT;
------ 암호화 필드
----------------------------------------------------------------------------------------
update domain
set DOMAIN_PWD_LOCK_COUNT = 0;

update users
set USERS_SMS_MAX_QUOTA = 0;

update users
set MAX_BIG_UPLOAD_SIZE = 0;

update users
set USERS_PWD_FAIL_COUNT = 0;

update user_group
set P_USER_GROUP_IDX = USER_GROUP_DEF;

alter table user_group drop column USER_GROUP_DEF;
alter table user_group drop column USER_GROUP_REF;

update user_group
set user_group_function = '111111111111';

insert into user_group 
(
USER_GROUP_IDX,
P_USER_GROUP_IDX,
DOMAIN,
USER_GROUP_NAME,
USER_GROUP_SORT_NO,
USER_GROUP_DEFAULT,
USER_GROUP_FUNCTION,
USER_GROUP_VOLUME,
USER_GROUP_MAIL,
USER_GROUP_SCHEDULE,
USER_GROUP_ADDRESS,
USER_GROUP_STRUCTURE,
USER_GROUP_SMS_QUOTA
)
values
(1,    0,    'naravision.net',    'naravision',    1,    0,     '111111111111',    500,                  1,     1,    1,    1,    200);

update user_group
set P_USER_GROUP_IDX = 1
where P_USER_GROUP_IDX = 0 and USER_GROUP_IDX != 1;

update user_group
set USER_GROUP_SORT_NO = 0;

update b_KEPETROORKR
set B_NOTICE_WAY = 0;

alter table bbs_userlog drop primary key;
alter table bbs_userlog add constraint pk_bbs_userlog primary key(BBS_USERLOG_IDX, USERS_IDX);
update bbs_userlog
set BBS_USERLOG_IDX = substr(BBS_USERLOG_IDX, instr(BBS_USERLOG_IDX, '_')+1);

update schedule
set P_SCHEDULE_IDX = 0;

update schedule aa
set user_group_idx = (select user_group_idx from user_group_list bb where aa.users_idx = bb.users_idx);

update schedule aa
set SCHEDULE_ALAM = 0;

update schedule aa
set SCHEDULE_ALAM_WAY = 0;

update bbs
set BBS_GROUP_IDX = 0
where BBS_GROUP_IDX = -1;

update mail_reconf
set M_IDX = 0;

update mail_reconf
set MAIL_RECONF_SEND = 1;

update users
set USERS_FWD_AUTH = 'Y';

insert into publicgroup(PUBLICGROUP_IDX,PUBLICGROUP_DEF,DOMAIN,PUBLICGROUP_NAME,PUBLICGROUP_SORT_NO)
values (1,    0,    'naravision.net',    'naravision', 0);

update publicgroup
set PUBLICGROUP_DEF = 1
where PUBLICGROUP_DEF = 0 and PUBLICGROUP_IDX != 1;

update users
set USERS_BOARD_AUTH = 'N';

alter table anaconda_file
modify
(
FILE_EXPIRE                VARCHAR2(10),
FILE_CREATE                VARCHAR2(10)
);


alter table anaconda_file_del
modify
(
FILE_EXPIRE                VARCHAR2(10),
FILE_CREATE                VARCHAR2(10)
);

update organize
set ORGANIZE_LEVEL = ORGANIZE_LEVEL+1;

CREATE INDEX IDX_SCHEDULE_SDATE
ON SCHEDULE
(
    SCHEDULE_SDATE DESC
)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 5M
    NEXT 5M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_INDX NOCOMPRESS NOPARALLEL;

CREATE INDEX IDX_SCHEDULE_EDATE
ON SCHEDULE
(
    SCHEDULE_EDATE DESC
)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
    INITIAL 5M
    NEXT 5M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
LOGGING TABLESPACE KP2_INDX NOCOMPRESS NOPARALLEL;

alter table users
modify (
MAX_BIG_UPLOAD_SIZE default 0,
USERS_PWD_FAIL_COUNT default 0);

alter table note_reconf
add (NOTE_TITLE                VARCHAR2(500));
