
function getCardMail(objForm){
  var strTempContent = "";
//  strTempContent = "<div class='k_puCard'>\n";
//  strTempContent += "<div class='k_puCard_fs'>\n";
//  strTempContent += "<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000'	codebase='http://active.macromedia.com/flash2/cabs/swflash.cab#version=4,0,0,0' id=intro2 width='400' height='271'>\n\n";
//  strTempContent += "<param name=movie value='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf'>\n\n";
//  strTempContent += "<param name=loop value=false><param name=menu value=false>\n<param name=quality value=high>\n<param name=scale value=exactfit>\n\n";
//  strTempContent += "<param name=salign value=T>\n<param name=devicefont value=true>\n\n";
//  strTempContent += "<embed src='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf>' loop=false menu=false quality=high scale=exactfit salign=T devicefont=true bgcolor=black width='400' height='271' type='application/x-shockwave-flash' pluginspage='http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash'></embed></object>\n\n";
//  strTempContent += "</div>\n";
//  strTempContent += "<div class='k_puCard_if'>\n";
//  strTempContent += "<div class='k_cardInfo'>\n";
//  strTempContent += "<div class='k_cardInfoT'>TO<em><strong>: </strong>"+objForm.CARD_TO.value+"</em></div>\n";
//  strTempContent += "<div class='k_cardInfoTt'>제목<em><strong>: </strong>"+objForm.M_TITLE.value+"</em></div>\n";
//  strTempContent += "<p class='k_cardTxView'>"+objForm.m_content.value+"</p>\n";
//  strTempContent += "<div class='k_cardInfoF'>FROM<em><strong>: </strong>"+objForm.CARD_FROM.value+"</em></div>";
//  strTempContent += "</div>\n";
//  strTempContent += "</div>\n";
//  strTempContent += "<div class='k_puCardDw'>카드 이미지가  보이지 않으시면 <a href='http://"+objForm.strUrl.value+"jsp/kor/ecard/ecard_popup_view.jsp?ECARD_IDX="+objForm.ECARD_IDX.value+"' target='_blank'>[이곳]</a>을 누르세요!</div>\n";
//  strTempContent += "</div>\n";
strTempContent += "<table width='100%' border='0' cellspacing='0' cellpadding='0'>";
strTempContent += "  <tr>";
strTempContent += "    <td style='background:#e8e8e8; text-align:center; padding:20px 0 20px 0;'>";
strTempContent += "    <table width='402' height='271px' border='0' cellspacing='0' cellpadding='0' style=' border:1px solid #cacaca;text-align:center; '>";
strTempContent += "      <tr>";
strTempContent += "        <td>";
strTempContent += "<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000'	codebase='http://active.macromedia.com/flash2/cabs/swflash.cab#version=4,0,0,0' id=intro2 width='400' height='271'>\n\n";
strTempContent += "<param name=movie value='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf'>\n\n";
strTempContent += "<param name=loop value=false><param name=menu value=false>\n<param name=quality value=high>\n<param name=scale value=exactfit>\n\n";
strTempContent += "<param name=salign value=T>\n<param name=devicefont value=true>\n\n";
strTempContent += "<embed src='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf>' loop=false menu=false quality=high scale=exactfit salign=T devicefont=true bgcolor=black width='400' height='271' type='application/x-shockwave-flash' pluginspage='http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash'></embed></object>\n\n";
strTempContent += "</td>";
strTempContent += "      </tr>";
strTempContent += "    </table>";
strTempContent += "    <table width='391' border='0' cellspacing='0' cellpadding='0'>";
strTempContent += "      <tr>";
strTempContent += "        <td height='20'></td>";
strTempContent += "      </tr>";
strTempContent += "      <tr>";
strTempContent += "        <td><img src='http://"+objForm.strUrl.value+"/images/kor/box/card_boxTop.gif' width='391' height='25' /></td>";
strTempContent += "      </tr>";
strTempContent += "      <tr>";
strTempContent += "        <td height='60' style='background:#f1f1f1;text-align:center;'><table width='369' border='0' cellspacing='0' cellpadding='0' style='margin:15px 0 15px 0'>";
strTempContent += "          <tr>";
strTempContent += "            <td width='59' height='25' style='color:#999999; text-align:left;font:14px 돋움,Dotum,AppleGothic,sans-serif;font-weight:bold; '>TO </td>";
strTempContent += "            <td width='310' style='color:#999999; text-align:left;font:12px 돋움,Dotum,AppleGothic,sans-serif;'><b>:</b> "+objForm.CARD_TO.value+" </td>";
strTempContent += "          </tr>";
strTempContent += "          <tr>";
strTempContent += "            <td height='21' style=' color:#999999; text-align:left;font:14px 돋움,Dotum,AppleGothic,sans-serif;font-weight:bold; '>제목</td>";
strTempContent += "            <td style='color:#999999; text-align:left;font:12px 돋움,Dotum,AppleGothic,sans-serif;'><b>:</b> "+objForm.M_TITLE.value+"</td>";
strTempContent += "          </tr>";
strTempContent += "        </table>";
strTempContent += "          <table width='369' height='115' border='0' cellspacing='0' cellpadding='0' style='border:1px solid #cccccc' >";
strTempContent += "            <tr>";
strTempContent += "              <td style='font-size:12px;color:#999999; text-align:left;font:12px 돋움,Dotum,AppleGothic,sans-serif; padding:5px; vertical-align:top'>"+objForm.m_content.value+"</td>";
strTempContent += "            </tr>";
strTempContent += "          </table></td>";
strTempContent += "      </tr>";
strTempContent += "      ";
strTempContent += "      <tr>";
strTempContent += "        <td style='background:#f1f1f1'>&nbsp;</td>";
strTempContent += "      </tr>";
strTempContent += "      <tr>";
strTempContent += "        <td style='color:#999999; text-align:left;font:11px 돋움,Dotum,AppleGothic,sans-serif; padding:5px;'>카드가 보이지 않으시면 ";
strTempContent += "        <a href='http://"+objForm.strUrl.value+"jsp/kor/ecard/ecard_popup_view.jsp?ECARD_IDX="+objForm.ECARD_IDX.value+"' target='_blank' style='color:#FF6666; text-decoration:none'>[이곳]</a>";
strTempContent += "      을 누르세요!  </td>";
strTempContent += "      </tr>";
strTempContent += "    </table></td>";
strTempContent += "  </tr>";
strTempContent += "</table>";

  return strTempContent;
}

//function getCardMail(objForm){
//  var strTempContent = "";
//  strTempContent = "<div class='k_puCard' style='position:relative'>\n";
//  strTempContent += "<div class='k_puCard_fs'>\n";
//  strTempContent += "<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000'	codebase='http://active.macromedia.com/flash2/cabs/swflash.cab#version=4,0,0,0' id=intro2 width='400' height='271'>\n\n";
//  strTempContent += "<param name=movie value='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf'>\n\n";
//  strTempContent += "<param name=loop value=false><param name=menu value=false>\n<param name=quality value=high>\n<param name=scale value=exactfit>\n\n";
//  strTempContent += "<param name=salign value=T>\n<param name=devicefont value=true>\n\n";
//  strTempContent += "<param name=wmode value=transparent>\n\n";
//  strTempContent += "<embed src='http://"+objForm.strUrl.value+"/images/common/ecard/"+objForm.ECARD_IDX.value+".swf>' loop=false menu=false quality=high scale=exactfit salign=T devicefont=true bgcolor=black width='400' height='271' type='application/x-shockwave-flash' pluginspage='http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash'></embed></object>\n\n";
//  strTempContent += "</div>\n";
//  strTempContent += "<div class='k_puCard_if'>\n";
//  strTempContent += "<div class='k_cardInfo'>\n";
//  strTempContent += "<div class='k_cardInfoT'>TO<em><strong>: </strong>"+objForm.CARD_TO.value+"</em></div>\n";
//  strTempContent += "<div class='k_cardInfoTt'>제목<em><strong>: </strong>"+objForm.M_TITLE.value+"</em></div>\n";
//  strTempContent += "<p class='k_cardTxView'>"+objForm.m_content.value+"</p>\n";
//  strTempContent += "<div class='k_cardInfoF'>FROM<em><strong>: </strong>"+objForm.CARD_FROM.value+"</em></div>";
//  strTempContent += "</div>\n";
//  strTempContent += "</div>\n";
//  strTempContent += "<div class='k_puCardDw'>카드가 보이지 않으시면 <a href='http://"+objForm.strUrl.value+"jsp/kor/ecard/ecard_popup_view.jsp?ECARD_IDX="+objForm.ECARD_IDX.value+"' target='_blank'>[이곳]</a>을 누르세요!</div>\n";
//  strTempContent += "</div>\n";
//
//  return strTempContent;
//}