DROP TABLE ECARD;

CREATE TABLE ECARD
(    CONSTRAINT ECARD_PK
     PRIMARY KEY (ECARD_IDX)
     USING INDEX TABLESPACE INDX
     storage(INITIAL 2m NEXT 200k pctincrease 0),
     ECARD_IDX     NUMBER(10)  NOT NULL,  /*인덱스(PK)*/
     ECARD_THEME   VARCHAR2(200)   NOT NULL,  /*카드 테마*/
     ECARD_TITLE   VARCHAR2(200),         /*카드 제목*/
     ECARD_DATE    DATE,                  /*카드 등록일시*/
     ECARD_SENDNUM NUMBER(9)                     /*발송횟수*/
)
pctfree 10
pctused 90
storage (initial 12M  next 2M  pctincrease 0);

DROP SEQUENCE SEQ_ECARD;

CREATE SEQUENCE SEQ_ECARD START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 CACHE 20 NOCYCLE  NOORDER;

INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'계절-날씨','당신의 별',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'계절-날씨','봄맞이',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'계절-날씨','비오는날',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'계절-날씨','햇살담아',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'계절-날씨','행복하세요',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','기다림',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','기다림2',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','꽃의연가',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','무서운병',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','사랑해서좋은사람',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'격려','알랙산더대왕의보물',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'우정','영원한우정',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'격려','오늘하루가',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','우산을들어줄',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'격려','의미있는삶',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'격려','커피한잔의여유',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'우정','friend',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'사랑','heart',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'근하신년','근하신년',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'근하신년','기원합니다',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'크리스마스','눈사람',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'크리스마스','루돌프사슴코',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'근하신년','밝아오는새해',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'근하신년','올해당신은',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'근하신년','유리구슬',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'크리스마스','즐거운성탄절',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'크리스마스','크리스마스방문',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'크리스마스','MerryChristmas',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'초대','꼭오세요',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'초대','초대-수화',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'초대','함께해요',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'생일','가을에태어난당신',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'축하-감사','감사',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'축하-감사','결혼행진',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'생일','너를위한케익',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'생일','오늘은말야',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'졸업','즐거웠던추억들',sysdate,0);
INSERT INTO ECARD(ECARD_IDX,ECARD_THEME,ECARD_TITLE,ECARD_DATE,ECARD_SENDNUM) VALUES(SEQ_ECARD.NEXTVAL,'졸업','졸업축하',sysdate,0);

