DROP TABLE DUAL;
CREATE TABLE DUAL
(
	IDX VARCHAR(10)
)lock mode row;
INSERT INTO DUAL VALUES('');

DROP TABLE ANACONDA_USERS;
CREATE TABLE ANACONDA_USERS
(
	USERS_IDX      VARCHAR(200) NOT NULL,
  	USERS_PERMIT   CHAR(1) NOT NULL,
  	FILE_HOMEDIR   VARCHAR(255) NOT NULL,
  	PERIOD_LIMIT_YN CHAR(1),
  	DOWN_LIMIT_YN  CHAR(1),
  	DOWN_CNT       NUMERIC(10),
  	USERS_MAXQUOTA NUMERIC(15),
  	USERS_PERIOD   NUMERIC(10),
  	EXPIRE_DEL_YN  CHAR(1),
  	FILE_WRITE_MODE CHAR(1) DEFAULT '0',
  	FILE_USE_MODE  CHAR(1) DEFAULT '0',
  	MAX_UPLOAD_SIZE  NUMERIC(15) ,
  	PRIMARY KEY (USERS_IDX) CONSTRAINT PK_ANACONDA_USERS 
)lock mode row;

DROP TABLE ANACONDA_USERGROUP;
CREATE TABLE ANACONDA_USERGROUP
(
  	USER_GROUP_IDX NUMERIC(9) NOT NULL,
  	SERVICE_YN     VARCHAR(1),
  	PERIOD_LIMIT_YN VARCHAR(1),
  	DOWN_LIMIT_YN  VARCHAR(1),
  	DOWN_CNT       NUMERIC(10),
  	USERGROUP_MAXQUOTA NUMERIC(15),
  	USERGROUP_PERIOD NUMERIC(10),
  	EXPIRE_DEL_YN  VARCHAR(1),
  	APPLYALL_YN    VARCHAR(1),
  	PRIMARY KEY (USER_GROUP_IDX) CONSTRAINT PK_ANACONDA_USERGROUP
)lock mode row;
DROP SEQUENCE SEQ_ANACONDA_USERGROUP;
CREATE SEQUENCE SEQ_ANACONDA_USERGROUP;

DROP TABLE ANACONDA_SHARE;
CREATE TABLE ANACONDA_SHARE
(
  	FILE_KEY       NUMERIC NOT NULL,
  	USERS_IDX      VARCHAR(200) NOT NULL,
  	DIR_PERMISSION CHAR(1),
  	CREATE_DATE    DATETIME YEAR TO SECOND,
  	UPDATE_DATE    DATETIME YEAR TO SECOND,
  	PRIMARY KEY (FILE_KEY) CONSTRAINT PK_ANACONDA_SHARE
)lock mode row;
DROP SEQUENCE SEQ_ANACONDA_SHARE;
CREATE SEQUENCE SEQ_ANACONDA_SHARE;

DROP TABLE ANACONDA_MAIL;
CREATE TABLE ANACONDA_MAIL
(
  	MAIL_KEY       NUMERIC(10) NOT NULL,
  	MAIL_SEQ       VARCHAR(128) NOT NULL,
  	USERS_IDX      VARCHAR(200) NOT NULL,
  	M_SENDER       VARCHAR(100),
  	M_TO           TEXT,
  	M_CC           TEXT,
  	M_BCC          TEXT,
  	MAIL_EXPIRE    VARCHAR(8),
  	MAIL_CREATE    VARCHAR(8),
  	PRIMARY KEY (MAIL_KEY) CONSTRAINT PK_ANACONDA_MAIL
)lock mode row;
DROP SEQUENCE SEQ_ANACONDA_MAIL;
CREATE SEQUENCE SEQ_ANACONDA_MAIL;

DROP TABLE ANACONDA_FILE;
CREATE TABLE ANACONDA_FILE
(
  FILE_KEY       NUMERIC(10) NOT NULL,
  FILE_SEQ       NUMERIC(10) NOT NULL,
  USERS_IDX      VARCHAR(200) NOT NULL,
  MAIL_SEQ       VARCHAR(200),
  FILE_NAME      VARCHAR(255),
  FILE_SUCCESS   VARCHAR(3),
  FILE_DIR       CHAR(1),
  FILE_SIZE      NUMERIC(15),
  DOWN_CNT       NUMERIC(10),
  FILE_EXPIRE    VARCHAR(8),
  FILE_CREATE    VARCHAR(8),
  FILE_DEL       CHAR(1),
  FILE_CNT       NUMERIC(5) DEFAULT 0,
  MAIL_YN        CHAR(1),
  SHARE_YN       CHAR(1) DEFAULT '0',
  FILE_CLIENT_DATE VARCHAR(12),
  FILE_ATTRIBUTE VARCHAR(10),
  DOWN_CNT_PERMIT NUMERIC(10) DEFAULT 0,
  PRIMARY KEY (FILE_KEY) CONSTRAINT PK_ANACONDA_FILE
)lock mode row;
DROP SEQUENCE SEQ_ANACONDA_FILE;
CREATE SEQUENCE SEQ_ANACONDA_FILE;

DROP TABLE ANACONDA_FILE_DEL;
CREATE TABLE ANACONDA_FILE_DEL
(
  FILE_KEY       NUMERIC(10) NOT NULL,
  FILE_SEQ       NUMERIC(10) NOT NULL,
  USERS_IDX      VARCHAR(200) NOT NULL,
  MAIL_SEQ       VARCHAR(128) NOT NULL,
  FILE_NAME      VARCHAR(255),
  FILE_SUCCESS   VARCHAR(3),
  FILE_DIR       CHAR(1),
  FILE_SIZE      NUMERIC(15),
  DOWN_CNT       NUMERIC(10),
  FILE_EXPIRE    VARCHAR(8),
  FILE_CREATE    VARCHAR(8),
  FILE_DEL       CHAR(1),
  FILE_CNT       NUMERIC(5) DEFAULT 0,
  MAIL_YN        CHAR(1),
  SHARE_YN       CHAR(1),
  FILE_CLIENT_DATE VARCHAR(12),
  FILE_ATTRIBUTE VARCHAR(10),
  DOWN_CNT_PERMIT NUMERIC(10) DEFAULT 0,
  PRIMARY KEY (FILE_KEY) CONSTRAINT PK_ANACONDA_FILE_DEL
)lock mode row;
DROP SEQUENCE SEQ_ANACONDA_FILE_DEL;
CREATE SEQUENCE SEQ_ANACONDA_FILE_DEL;

DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT (
  ACCOUNT_IDX VARCHAR(200) DEFAULT '' NOT NULL PRIMARY KEY,
  USERS_IDX VARCHAR(200) DEFAULT '' NOT NULL,
  DOMAIN VARCHAR(100) DEFAULT '' NOT NULL,
  MBOX_IDX INTEGER DEFAULT 0 NOT NULL,
  ACCOUNT_ISVALID SMALLINT DEFAULT 0 NOT NULL,
  ACCOUNT_ISDATED SMALLINT DEFAULT 0 NOT NULL,
  ACCOUNT_SDATE DATETIME YEAR TO SECOND,
  ACCOUNT_EDATE DATETIME YEAR TO SECOND
)lock mode row;
CREATE INDEX INDEX_ACCOUNT_USERS_IDX ON ACCOUNT(USERS_IDX);
CREATE INDEX INDEX_ACCOUNT_DOMAIN ON ACCOUNT(DOMAIN);

DROP TABLE ADDRESS;
CREATE TABLE ADDRESS
(
  ADDRESS_IDX    NUMERIC PRIMARY KEY,
  P_ADDRESS_IDX NUMERIC DEFAULT 0,
  USERS_IDX      VARCHAR(200) NOT NULL,
  GROUP_IDX      NUMERIC NOT NULL,
  ADDRESS_NAME   VARCHAR(100),
  ADDRESS_SORT_NO NUMERIC NOT NULL,
  ADDRESS_EMAIL  VARCHAR(200),
  ADDRESS_TEL    VARCHAR(100),
  ADDRESS_CELLTEL VARCHAR(100),
  ADDRESS_HOMEZIP VARCHAR(100),
  ADDRESS_HOMEADDR VARCHAR(100),
  ADDRESS_OFFICE VARCHAR(100),
  ADDRESS_DEPT   VARCHAR(100),
  ADDRESS_DUTY   VARCHAR(100),
  ADDRESS_OFFICETEL VARCHAR(100),
  ADDRESS_OFFICEZIP VARCHAR(100),
  ADDRESS_OFFICEADDR VARCHAR(100),
  ADDRESS_BIRTH  VARCHAR(100),
  ADDRESS_ISSOLAR CHAR(1),
  ADDRESS_HOMEURL VARCHAR(200),
  ADDRESS_STMT   LVARCHAR(4000),
  ADDRESS_OFFICEFAX VARCHAR(100)
)lock mode row;
DROP SEQUENCE SEQ_ADDRESS;
CREATE SEQUENCE SEQ_ADDRESS; 
CREATE INDEX IDX1_ADDRESS
   ON ADDRESS(USERS_IDX, GROUP_IDX, ADDRESS_SORT_NO
);
CREATE INDEX IDX2_ADDRESS
   ON ADDRESS(GROUP_IDX, ADDRESS_SORT_NO
);

DROP TABLE ADDRESS_GROUP;
CREATE TABLE ADDRESS_GROUP
(
  GROUP_IDX      NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  GROUP_NM       LVARCHAR(1000) NOT NULL,
  GROUP_SORT_NO  NUMERIC NOT NULL,
  DOMAIN         VARCHAR(100) NOT NULL,
  REF_GROUP_IDX  NUMERIC NOT NULL,
  GROUP_STMT     LVARCHAR(1000),
  GROUP_TYPE     CHAR(1) DEFAULT 'U'  NOT NULL
)lock mode row;
CREATE INDEX IDX1_ADDRESS_GROUP
   ON ADDRESS_GROUP(USERS_IDX);
CREATE INDEX IDX2_ADDRESS_GROUP
   ON ADDRESS_GROUP(DOMAIN, GROUP_SORT_NO);
CREATE INDEX IDX3_ADDRESS_GROUP
   ON ADDRESS_GROUP(REF_GROUP_IDX);
DROP SEQUENCE SEQ_ADDRESS_GROUP;
CREATE SEQUENCE SEQ_ADDRESS_GROUP;   

DROP TABLE AUTHORITY;
CREATE TABLE AUTHORITY
(
  AUTHORITY_IDX  	NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         	VARCHAR(100) NOT NULL,
  AUTHORITY_NAME 	VARCHAR(100),
  AUTHORITY_LEVEL NUMERIC 
)lock mode row; 
DROP SEQUENCE SEQ_AUTHORITY;
CREATE SEQUENCE SEQ_AUTHORITY;

DROP TABLE AUTODIVISION;
CREATE TABLE AUTODIVISION
(
  AUTODIVISION_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  MBOX_IDX       NUMERIC,
  AUTODIVISION_TYPE NUMERIC(1),
  AUTODIVISION_KEYWORD VARCHAR(200),
  NOTICE         NUMERIC DEFAULT 0,
  TAG_TYPE       NUMERIC DEFAULT 0
)lock mode row;
CREATE INDEX INDEX_AUTODIVISION_USERS_IDX
  ON AUTODIVISION(USERS_IDX);
DROP SEQUENCE SEQ_AUTODIVISION;
CREATE SEQUENCE SEQ_AUTODIVISION;

DROP TABLE BASEINFO;
CREATE TABLE BASEINFO
(
  BASEINFO_TYPE  CHAR(1),
  BASEINFO_ID    CHAR(4) NOT NULL,
  BASEINFO_VALUE VARCHAR(100)
)lock mode row;

DROP TABLE BBS;
CREATE TABLE BBS
(
  BBS_IDX        				NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         				VARCHAR(100),
  BBS_ADMIN      				VARCHAR(200),
  BBS_TYPE       				NUMERIC(1),
  BBS_MODE       				NUMERIC(1),
  BBS_GROUP_IDX  				NUMERIC(9),
  BBS_NAME       				LVARCHAR(1000),
  BBS_USE_REPLY  				NUMERIC(1),
  BBS_USE_ATTACHE 			NUMERIC(1),
  BBS_USE_APPEND 				NUMERIC(1),
  BBS_USE_ATTACHE_SIZE 	NUMERIC(5),
  BBS_AUTH_MEMBER 			NUMERIC(1),
  BBS_AUTH_GUEST 				NUMERIC(1),
  BBS_AUTH_HIGHER 			NUMERIC(1),
  BBS_AUTH_LOWER 				NUMERIC(1),
  BBS_AUTH_EQUALTY 			NUMERIC(1)
)lock mode row;
DROP SEQUENCE SEQ_BBS;
CREATE SEQUENCE SEQ_BBS;

DROP TABLE BBS_GROUP;
CREATE TABLE BBS_GROUP
(
  BBS_GROUP_IDX  		NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         		VARCHAR(100),
  BBS_GROUP_NAME 		VARCHAR(100),
  BBS_GROUP_LEVEL 	NUMERIC(9)
)lock mode row;
DROP SEQUENCE SEQ_BBS_GROUP;
CREATE SEQUENCE SEQ_BBS_GROUP;

DROP TABLE BBS_TOP;
CREATE TABLE BBS_TOP
(
  BBS_IDX        NUMERIC(9) NOT NULL,
  B_IDX          NUMERIC(10) NOT NULL,
  PRIMARY KEY (BBS_IDX, B_IDX)
)lock mode row;


DROP TABLE BBS_USERLOG;
CREATE TABLE BBS_USERLOG
(
  BBS_USERLOG_IDX NUMERIC NOT NULL,
  USERS_IDX      VARCHAR(200) NOT NULL,
  BBS_USERLOG_DATE VARCHAR(20),
  PRIMARY KEY (BBS_USERLOG_IDX, USERS_IDX) CONSTRAINT PK_USERLOG
)lock mode row;

DROP TABLE CERTIFY;
CREATE TABLE CERTIFY
(
  CERTIFY_IDX    NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  CERTIFY_ISVALID CHAR(1),
  CERTIFY_NAME   VARCHAR(200),
  CERTIFY_JUMIN1 VARCHAR(6),
  CERTIFY_JUMIN2 VARCHAR(7),
  CERTIFY_DEPARTMENT VARCHAR(100),
  CERTIFY_LICENCENUM VARCHAR(200)
)lock mode row;
DROP SEQUENCE SEQ_CERTIFY;
CREATE SEQUENCE SEQ_CERTIFY;

DROP TABLE DOMAIN;
CREATE TABLE DOMAIN
(
  DOMAIN         				VARCHAR(100) NOT NULL,
  DOMAIN_TYPE    				CHAR(1),
  DOMAIN_NAME    				VARCHAR(100),
  DOMAIN_JOB     				VARCHAR(4),
  DOMAIN_TEL     				VARCHAR(20),
  DOMAIN_ZIPCODE 				VARCHAR(10),
  DOMAIN_ADDRESS1 			VARCHAR(100),
  DOMAIN_ADDRESS2 			VARCHAR(100),
  DOMAIN_HOMEPAGE 			VARCHAR(100),
  DOMAIN_AGREEMENT 			CHAR(1),
  DOMAIN_AGREEMENT_STMT 	LVARCHAR(4000),
  DOMAIN_GREETINGS 			CHAR(1),
  DOMAIN_GREETINGS_FROM 	VARCHAR(200),
  DOMAIN_GREETINGS_TITLE 	LVARCHAR(1000),
  DOMAIN_GREETINGS_CONTENTTYPE VARCHAR(20),
  DOMAIN_GREETINGS_CONTENT LVARCHAR(4000),
  DOMAIN_CERTIFY CHAR(1),
  DOMAIN_JOIN_CERTIFY CHAR(1),
  DOMAIN_JOIN_CERTIFY_OPT CHAR(1),
  DOMAIN_JOIN_WAY NUMERIC(1),
  DOMAIN_GROUP_OPT NUMERIC(1),
  DOMAIN_JOIN_REQUIRED_ITEM VARCHAR(100),
  DOMAIN_JOIN_CERTIFY_ITEM VARCHAR(100),
  DOMAIN_JOINDATE DATETIME YEAR TO SECOND,
  DOMAIN_LANG    VARCHAR(10),
  DOMAIN_USE_FILE CHAR(1),
  DOMAIN_DISPLAY_TOP CHAR(1),
  DOMAIN_DISPLAY_BOTTOM CHAR(1),
  DOMAIN_DISPLAY_MENU CHAR(1),
  DOMAIN_DISPLAY_MENU_POSITION CHAR(1),
  DOMAIN_TABLE_PIX NUMERIC(4),
  DOMAIN_TOP_PIX NUMERIC(3),
  DOMAIN_LEFT_SPACE NUMERIC(3),
  DOMAIN_BOTTOM_SPACE NUMERIC(3),
  DOMAIN_DISPLAY_BGIMG CHAR(1),
  DOMAIN_BGIMG   VARCHAR(50),
  DOMAIN_BGCOLOR VARCHAR(10),
  DOMAIN_TXT_COPY VARCHAR(200),
  DOMAIN_COLOR_SKIN CHAR(1),
  DOMAIN_COLOR_TXT VARCHAR(10),
  DOMAIN_COLOR_TOPTXT VARCHAR(10),
  DOMAIN_BGCOLOR_MENU VARCHAR(10),
  DOMAIN_BGCOLOR_BTN VARCHAR(10),
  DOMAIN_COLOR_ALINK VARCHAR(10),
  DOMAIN_BGCOLOR_TOP VARCHAR(10),
  DOMAIN_BGCOLOR_TABLE VARCHAR(10),
  DOMAIN_COLOR_TABLELINE VARCHAR(10),
  DOMAIN_COLOR_COPY VARCHAR(10),
  DOMAIN_TOP_HTML_USE CHAR(1),
  DOMAIN_TOP_HTML VARCHAR(50),
  DOMAIN_TOP_BGCOLOR VARCHAR(10),
  DOMAIN_DISPLAY_TOP_BGIMG CHAR(1),
  DOMAIN_TOP_BGIMG VARCHAR(50),
  DOMAIN_TOP_BTN NUMERIC(2),
  DOMAIN_TOP_BTNCOLOR VARCHAR(10),
  DOMAIN_TOP_MENU_POS NUMERIC(1),
  DOMAIN_DISPLAY_LOGO CHAR(1),
  DOMAIN_LOGO    VARCHAR(50),
  DOMAIN_LOGO_TXT VARCHAR(200),
  DOMAIN_LOGO_TXTCOLOR VARCHAR(10),
  DOMAIN_BTN_CNT NUMERIC(1),
  DOMAIN_TABLE_POS CHAR(1),
  DOMAIN_INPUT_TXT VARCHAR(10),
  DOMAIN_LOGO_LINK VARCHAR(50),
  DOMAIN_MOTO_USE CHAR(1),
  DOMAIN_MENU_PIX NUMERIC(3),
  DOMAIN_BTN1_TITLE VARCHAR(40),
  DOMAIN_BTN1_LINK VARCHAR(40),
  DOMAIN_BTN1_TARGET VARCHAR(40),
  DOMAIN_BTN1_ALT VARCHAR(60),
  DOMAIN_BTN2_TITLE VARCHAR(40),
  DOMAIN_BTN2_LINK VARCHAR(40),
  DOMAIN_BTN2_TARGET VARCHAR(40),
  DOMAIN_BTN2_ALT VARCHAR(60),
  DOMAIN_BTN3_TITLE VARCHAR(40),
  DOMAIN_BTN3_LINK VARCHAR(40),
  DOMAIN_BTN3_TARGET VARCHAR(40),
  DOMAIN_BTN3_ALT VARCHAR(60),
  DOMAIN_BTN4_TITLE VARCHAR(40),
  DOMAIN_BTN4_LINK VARCHAR(40),
  DOMAIN_BTN4_TARGET VARCHAR(40),
  DOMAIN_BTN4_ALT VARCHAR(60),
  DOMAIN_BTN5_TITLE VARCHAR(40),
  DOMAIN_BTN5_LINK VARCHAR(40),
  DOMAIN_BTN5_TARGET VARCHAR(40),
  DOMAIN_BTN5_ALT VARCHAR(60),
  DOMAIN_BTN6_TITLE VARCHAR(40),
  DOMAIN_BTN6_LINK VARCHAR(40),
  DOMAIN_BTN6_TARGET VARCHAR(40),
  DOMAIN_BTN6_ALT VARCHAR(60),
  DOMAIN_BTN7_TITLE VARCHAR(40),
  DOMAIN_BTN7_LINK VARCHAR(40),
  DOMAIN_BTN7_TARGET VARCHAR(40),
  DOMAIN_BTN7_ALT VARCHAR(60),
  DOMAIN_FUNCTION_KEY VARCHAR(20),
  DOMAIN_LIMIT_STORAGE NUMERIC(9),
  DOMAIN_LIMIT_USERS NUMERIC(9),
  DOMAIM_LIMIT_FORWARD NUMERIC(9),
  DOMAIN_LIMIT_UPLOAD NUMERIC(9),
  DOMAIN_MEMO    LVARCHAR(4000),
  DOMAIN_USER_VOLUME NUMERIC(9),
  DOMAIN_SMS_LIMIT NUMERIC(9),
  DOMAIN_SMS_DATE DATETIME YEAR TO SECOND,
  DOMAIN_MAIL_QUOTA NUMERIC(10) DEFAULT 0  NOT NULL,
  DOMAIN_MAIL_BANNER NUMERIC(1) DEFAULT 0  NOT NULL,
  DOMAIN_MAIL_BANNER_TEXT LVARCHAR(2000),
  DOMAIN_ACCOUNT_LIMIT NUMERIC(3) DEFAULT 0  NOT NULL,
  DOMAIN_PAUSE_DAYS NUMERIC(9) DEFAULT 0  NOT NULL,
  DOMAIN_EXPIREDDATE DATETIME YEAR TO SECOND,
  DOMAIN_BIGMAIL_QUOTA NUMERIC(15) DEFAULT 0,
  PRIMARY KEY (DOMAIN) CONSTRAINT PK_DOMAIN
)lock mode row;

DROP TABLE ECARD;
CREATE TABLE ECARD
(
  ECARD_IDX      NUMERIC NOT NULL PRIMARY KEY,
  ECARD_THEME    VARCHAR(200) NOT NULL,
  ECARD_TITLE    VARCHAR(200),
  ECARD_DATE     DATETIME YEAR TO SECOND,
  ECARD_SENDNUM  NUMERIC(9)
)lock mode row;
DROP SEQUENCE SEQ_ECARD;
CREATE SEQUENCE SEQ_ECARD;

DROP TABLE FILE_SHARE;
CREATE TABLE FILE_SHARE
(
  FILE_SHARE_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  FILE_SHARE_FOLDER LVARCHAR(2000),
  FILE_SHARE_AUTH CHAR(1)
)lock mode row;
DROP SEQUENCE SEQ_FILE_SHARE;
CREATE SEQUENCE SEQ_FILE_SHARE;

DROP TABLE FILTER;
CREATE TABLE FILTER
(
  FILTER_IDX     NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  FILTER_AUTH    NUMERIC(1),
  FILTER_TYPE    NUMERIC(1),
  FILTER_KEYWORD VARCHAR(200)
)lock mode row;
CREATE INDEX INDEX_FILTER_FILTER_AUTH
   ON FILTER(FILTER_AUTH);
CREATE INDEX INDEX_FILTER_USERS_IDX
   ON FILTER(USERS_IDX);
DROP SEQUENCE SEQ_FILTER;
CREATE SEQUENCE SEQ_FILTER;

DROP TABLE FORMLETTER;
CREATE TABLE FORMLETTER
(
  FORMLETTER_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  FORMLETTER_TYPE NUMERIC(3),
  FORMLETTER_SUBJECT VARCHAR(200),
  CONTENT        LVARCHAR(30000)
)lock mode row;
DROP SEQUENCE SEQ_FORMLETTER;
CREATE SEQUENCE SEQ_FORMLETTER;

DROP TABLE INJURE;
CREATE TABLE INJURE
(
  INJURE_IDX     NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  INJURE_AUTH    NUMERIC(1),
  INJURE_KEYWORD VARCHAR(200)
)lock mode row;
CREATE INDEX IDX_INJURE_USER_IDX
   ON INJURE(USERS_IDX);
DROP SEQUENCE SEQ_INJURE;
CREATE SEQUENCE SEQ_INJURE;

DROP TABLE IP_BLOCKING;
CREATE TABLE IP_BLOCKING
(
  IP             VARCHAR(100) NOT NULL,
  WHITE_IP       CHAR(1) NOT NULL,
  BLACK_IP       CHAR(1) NOT NULL,
  DYNAMIC_IP     CHAR(1) NOT NULL,
  REGISTER_DATE  DATETIME YEAR TO SECOND,
  VALID_DATE     DATETIME YEAR TO SECOND,
  PRIMARY KEY (IP) CONSTRAINT PK_IP_BLOCKING
)lock mode row;

DROP TABLE MAIL_LOG;
CREATE TABLE MAIL_LOG
(
  MAIL_LOG_DATE  DATETIME YEAR TO SECOND,
  MAIL_LOG_DOMAIN VARCHAR(100) NOT NULL,
  MAIL_LOG_RECEIVE_COUNT NUMERIC(10) DEFAULT 0,
  MAIL_LOG_SEND_COUNT NUMERIC(10) DEFAULT 0,
  MAIL_LOG_RECEIVE_VOLUME NUMERIC(20) DEFAULT 0,
  MAIL_LOG_SEND_VOLUME NUMERIC(20) DEFAULT 0,
  MAIL_LOG_ERROR_COUNT NUMERIC(10) DEFAULT 0,
  PRIMARY KEY(MAIL_LOG_DATE, MAIL_LOG_DOMAIN) CONSTRAINT PK_MAIL_LOG
)lock mode row;

DROP TABLE MAIL_RECONF;
CREATE TABLE MAIL_RECONF
(
  MAIL_RECONF_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  MAIL_RECONF_TO VARCHAR(200) NOT NULL,
  MAIL_RECONF_SUBJECT LVARCHAR(4000),
  MAIL_RECONF_STATE NUMERIC(1),
  MAIL_RECONF_SDATE VARCHAR(20),
  MAIL_RECONF_RDATE VARCHAR(20),
  MAIL_RECONF_MESSAGE_ID VARCHAR(255),
  M_IDX          NUMERIC(10),
  MAIL_RECONF_GROUP NUMERIC(14),
  MAIL_RECONF_SEND CHAR(1) DEFAULT '0',
  MAIL_RECONF_SEND_DATE VARCHAR(20)
)lock mode row;
CREATE INDEX IDX_MAIL_RECONF_MESSAGE_ID
   ON MAIL_RECONF(MAIL_RECONF_MESSAGE_ID);
CREATE INDEX IDX_MAIL_RECONF_M_IDX
   ON MAIL_RECONF(M_IDX);
DROP SEQUENCE SEQ_MAIL_RECONF;
CREATE SEQUENCE SEQ_MAIL_RECONF;

DROP TABLE MAIL_REPORT;
CREATE TABLE MAIL_REPORT
(
  MAIL_REPORT_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_IDX      VARCHAR(200) NOT NULL,
  USERS_NAME     VARCHAR(20),
  MAIL_REPORT_DATE VARCHAR(20),
  MAIL_REPORT_FROM VARCHAR(200),
  MAIL_REPORT_SENDDATE VARCHAR(20),
  MAIL_REPORT_STMT LVARCHAR(4000),
  MAIL_REPORT_STATE NUMERIC(1)
)lock mode row;
DROP SEQUENCE SEQ_MAIL_REPORT;
CREATE SEQUENCE SEQ_MAIL_REPORT;

DROP TABLE MBOX;
CREATE TABLE MBOX
(
  MBOX_IDX       NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  MBOX_TYPE      NUMERIC(3) NOT NULL,
  MBOX_REF       NUMERIC(10) DEFAULT 0  NOT NULL,
  MBOX_NAME      VARCHAR(50),
  MBOX_SIZE      NUMERIC(20),
  MBOX_MAILCOUNT NUMERIC(6),
  MBOX_SUBSCRIBE CHAR(1) DEFAULT 'Y'
)lock mode row;
CREATE INDEX IDX_MBOX_01
   ON MEMBER(USERS_IDX, MBOX_TYPE);
DROP SEQUENCE SEQ_MBOX;
CREATE SEQUENCE SEQ_MBOX;

DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
  MEMBER_IDX     NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_IDX      VARCHAR(200) NOT NULL,
  ORGANIZE_IDX   NUMERIC(9) NOT NULL,
  AUTHORITY_IDX  NUMERIC(9)
)lock mode row;
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER;
CREATE INDEX IDX_MEMBER_ORGANIZE_IDX
   ON MEMBER(ORGANIZE_IDX);
CREATE INDEX IDX_MEMBER_DOMAIN
   ON MEMBER(DOMAIN);

DROP TABLE MEMO;
CREATE TABLE MEMO
(
  MEMO_IDX       NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(25) NOT NULL,
  MEMO_COLOR     VARCHAR(20) NOT NULL,
  MEMO_CONTENT   LVARCHAR(2000) NOT NULL,
  DIPLAY_YN      CHAR(1) NOT NULL,
  CREATE_DATE    DATETIME YEAR TO SECOND,
  UPDATE_DATE    DATETIME YEAR TO SECOND
)lock mode row;   
DROP SEQUENCE SEQ_MEMO;
CREATE SEQUENCE SEQ_MEMO;

DROP TABLE MONITOR_MAIL_LOG;
CREATE TABLE MONITOR_MAIL_LOG
(
  MAIL_ID        VARCHAR(100) NOT NULL,
  MAIL_HOSTNAME  VARCHAR(40) NOT NULL,
  MAIL_CREATE_DATE DATETIME YEAR TO SECOND NOT NULL,
  MAIL_RESULT_DATE DATETIME YEAR TO SECOND,
  MAIL_DELETE_DATE DATETIME YEAR TO SECOND,
  MAIL_ORIGIN    VARCHAR(10) NOT NULL,
  MAIL_DESTINATION VARCHAR(10) NOT NULL,
  MAIL_DOMAIN    VARCHAR(40),
  MAIL_IP        VARCHAR(40),
  LOG_ID         VARCHAR(100) NOT NULL,
  MAIL_SENDER    VARCHAR(100) NOT NULL,
  MAIL_RECIPIENT VARCHAR(100) NOT NULL,
  MAIL_TYPE      VARCHAR(10) NOT NULL,
  MAIL_RESULT    CHAR(1),
  MAIL_VOLUME    NUMERIC(20) DEFAULT 0,
  MAIL_MESSAGE   VARCHAR(200),
  PRIMARY KEY (MAIL_ID, MAIL_HOSTNAME) CONSTRAINT PK_MONITOR_MAIL_LOG
)lock mode row;

DROP TABLE ORGANIZE;
CREATE TABLE ORGANIZE
(
  ORGANIZE_IDX   NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  ORGANIZE_REF   NUMERIC(9),
  ORGANIZE_STEP  NUMERIC(9),
  ORGANIZE_LEVEL NUMERIC(9),
  ORGANIZE_DEF   NUMERIC(9),
  ORGANIZE_ADMIN VARCHAR(200),
  ORGANIZE_NAME  VARCHAR(100),
  ORGANIZE_TITLE VARCHAR(200),
  ORGANIZE_OPERATION LVARCHAR(1000),
  ORGANIZE_STMT  LVARCHAR(4000),
  ORGANIZE_SCHEDULE NUMERIC(1),
  ORGANIZE_SCHEDULE_HIGHER NUMERIC(1),
  ORGANIZE_SCHEDULE_LOWER NUMERIC(1),
  ORGANIZE_SCHEDULE_EQUALTY NUMERIC(1)
)lock mode row;
DROP SEQUENCE SEQ_ORGANIZE;
CREATE SEQUENCE SEQ_ORGANIZE;

DROP TABLE PASSWD_HINT;
CREATE TABLE PASSWD_HINT
(
  USERS_IDX      VARCHAR(200) NOT NULL,
  PASSWD_HINT_QUESTION NUMERIC(2) NOT NULL,
  PASSWD_HINT_ANSWER VARCHAR(200) NOT NULL,
  PRIMARY KEY (USERS_IDX) CONSTRAINT PK_PASSWD_HINT
)lock mode row;

DROP TABLE POLL;
CREATE TABLE POLL
(
  POLL_IDX       NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  DOMAIN         VARCHAR(100),
  POLL_CONTENT   LVARCHAR(2000),
  POLL_SDATE     DATETIME YEAR TO SECOND,
  POLL_EDATE     DATETIME YEAR TO SECOND,
  POLL_PROGRESS  CHAR(1)
)lock mode row;
DROP SEQUENCE SEQ_POLL;
CREATE SEQUENCE SEQ_POLL;

DROP TABLE POLL_ITEM;
CREATE TABLE POLL_ITEM
(
  POLL_IDX       NUMERIC NOT NULL PRIMARY KEY,
  POLL_ITEM_NUM  NUMERIC(2),
  POLL_ITEM_CONTENT LVARCHAR(1000),
  POLL_ITEM_SUM  NUMERIC(6)
)lock mode row;
DROP SEQUENCE SEQ_POLL_ITEM;
CREATE SEQUENCE SEQ_POLL_ITEM;

DROP TABLE POLL_lIST;
CREATE TABLE POLL_LIST
(
  POLL_IDX       NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(100)
)lock mode row;
DROP SEQUENCE SEQ_POLL_LIST;
CREATE SEQUENCE SEQ_POLL_LIST;

DROP TABLE POP;
CREATE TABLE POP
(
  POP_IDX        NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  POP_PROTOCOL   VARCHAR(200),
  POP_SERVER     VARCHAR(200),
  POP_ID         VARCHAR(200),
  POP_PASSWD     VARCHAR(200),
  MBOX_IDX       NUMERIC(9),
  POP_ISDEL      VARCHAR(1),
  POP_MBOX       VARCHAR(100),
  POP_NAME       VARCHAR(50),
  POP_ICON       CHAR(1)
)lock mode row;
DROP SEQUENCE SEQ_POP;
CREATE SEQUENCE SEQ_POP;

DROP TABLE POP_BEFORE_SMTP;
CREATE TABLE POP_BEFORE_SMTP
(
  IP_ADDRESS     VARCHAR(100) NOT NULL PRIMARY KEY,
  SESSION_TIME   DATETIME YEAR TO SECOND NOT NULL
)lock mode row;


DROP TABLE PUBLICADDRESS;
CREATE TABLE PUBLICADDRESS
(
  PUBLICADDRESS_IDX NUMERIC NOT NULL PRIMARY KEY,
  PUBLICGROUP_IDX NUMERIC(9) NOT NULL,
  DOMAIN         VARCHAR(100) NOT NULL,
  PUBLICADDRESS_NAME VARCHAR(100),
  PUBLICADDRESS_DEPT VARCHAR(100),
  PUBLICADDRESS_DUTY VARCHAR(100),
  PUBLICADDRESS_EMAIL VARCHAR(200),
  PUBLICADDRESS_TEL VARCHAR(100),
  PUBLICADDRESS_CELLTEL VARCHAR(100),
  PUBLICADDRESS_HOMEZIP VARCHAR(100),
  PUBLICADDRESS_HOMEADDR VARCHAR(100),
  PUBLICADDRESS_SORT_NO NUMERIC
)lock mode row;
DROP SEQUENCE SEQ_PUBLICADDRESS;
CREATE SEQUENCE SEQ_PUBLICADDRESS;


DROP TABLE PUBLICGROUP;
CREATE TABLE PUBLICGROUP
(
  PUBLICGROUP_IDX NUMERIC NOT NULL PRIMARY KEY,
  PUBLICGROUP_DEF NUMERIC(9) NOT NULL,
  DOMAIN         VARCHAR(100) NOT NULL,
  PUBLICGROUP_NAME VARCHAR(200) NOT NULL,
  PUBLICGROUP_SORT_NO NUMERIC
)lock mode row;
DROP SEQUENCE SEQ_PUBLICGROUP;
CREATE SEQUENCE SEQ_PUBLICGROUP;
CREATE INDEX IDX_PUBLICGROUP_DEF
   ON PUBLICGROUP(PUBLICGROUP_DEF);


DROP TABLE RESERVATION;
CREATE TABLE RESERVATION
(
  RESERVATION_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  RESERVATION_TO LVARCHAR(4000),
  RESERVATION_FILE VARCHAR(200),
  RESERVATION_TIME DATETIME YEAR TO SECOND,
  MAIL_RECONF_IDX NUMERIC(10) NOT NULL
)lock mode row;
DROP SEQUENCE SEQ_RESERVATION;
CREATE SEQUENCE SEQ_RESERVATION;

DROP TABLE RESERVEID;
CREATE TABLE RESERVEID
(
  RESERVEID_IDX  NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  RESERVEID_ID   VARCHAR(100)
)lock mode row;
DROP SEQUENCE SEQ_RESERVEID;
CREATE SEQUENCE SEQ_RESERVEID;


DROP TABLE SCHEDULE;
CREATE TABLE SCHEDULE
(
  SCHEDULE_IDX   NUMERIC NOT NULL PRIMARY KEY,
  P_SCHEDULE_IDX NUMERIC(9),
  USERS_IDX      VARCHAR(200),
  USERS_NAME     VARCHAR(100),
  DOMAIN         VARCHAR(100),
  USER_GROUP_IDX NUMERIC(9),
  SCHEDULE_SHARE NUMERIC(1),
  SCHEDULE_TYPE  NUMERIC(1),
  SCHEDULE_TITLE VARCHAR(200),
  SCHEDULE_STMT  LVARCHAR(2000),
  SCHEDULE_SDATE DATETIME YEAR TO SECOND,
  SCHEDULE_EDATE DATETIME YEAR TO SECOND,
  SCHEDULE_REPEAT NUMERIC(1),
  SCHEDULE_DAYLY NUMERIC(1),
  SCHEDULE_ALAM  NUMERIC(1),
  SCHEDULE_ALAM_DATE DATETIME YEAR TO SECOND,
  SCHEDULE_ALAM_WAY NUMERIC(1),
  SCHEDULE_DDAY  NUMERIC(1),
  SHARE_GROUP_IDX VARCHAR(200)
)lock mode row;
DROP SEQUENCE SEQ_SCHEDULE;
CREATE SEQUENCE SEQ_SCHEDULE;
CREATE INDEX IDX1_SCHEDULE
   ON SCHEDULE(USERS_IDX, SCHEDULE_SDATE, SCHEDULE_EDATE);
CREATE INDEX IDX2_SCHEDULE
   ON SCHEDULE(DOMAIN, SCHEDULE_SDATE, SCHEDULE_EDATE);
CREATE INDEX IDX3_SCHEDULE
   ON SCHEDULE(SCHEDULE_SDATE, SCHEDULE_EDATE);

DROP TABLE SHARE_GROUP;
CREATE TABLE SHARE_GROUP
(
  SHARE_GROUP_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  SHARE_GROUP_DEF NUMERIC,
  SHARE_GROUP_REF NUMERIC,
  SHARE_GROUP_NAME VARCHAR(255) NOT NULL,
  SHARE_GROUP_DEFAULT NUMERIC,
  SHARE_GROUP_HOMEDIR VARCHAR(255),
  SHARE_GROUP_QUOTA NUMERIC(20),
  SHARE_GROUP_STATUS CHAR(1) DEFAULT 'S'
)lock mode row;
DROP SEQUENCE SEQ_SHARE_GROUP;
CREATE SEQUENCE SEQ_SHARE_GROUP;

DROP TABLE SHARE_GROUP_LIST;
CREATE TABLE SHARE_GROUP_LIST
(
  SHARE_GROUP_LIST_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_IDX      VARCHAR(255) NOT NULL,
  SHARE_GROUP_IDX NUMERIC NOT NULL,
  SHARE_STATUS   CHAR(1) DEFAULT 'S' ,
  SHARE_AUTH     VARCHAR(2) DEFAULT '10'  NOT NULL
)lock mode row;
DROP SEQUENCE SEQ_SHARE_GROUP_LIST;
CREATE SEQUENCE SEQ_SHARE_GROUP_LIST;
CREATE INDEX IDX_SHARE_GROUP_LIST
   ON SHARE_GROUP_LIST(USERS_IDX);
CREATE INDEX IDX2_SHARE_GROUP_LIST
   ON SHARE_GROUP_LIST(SHARE_GROUP_IDX);

DROP TABLE SMS;
CREATE TABLE SMS
(
  SERIALNO       NUMERIC NOT NULL PRIMARY KEY, 
  DESTCALLNO     VARCHAR(16) DEFAULT NULL,
  CALLBACKNO     VARCHAR(16) DEFAULT NULL,
  DATA           VARCHAR(200) DEFAULT NULL,
  JEOBSU_TIME    DATETIME YEAR TO SECOND,
  YEYAK_TIME     DATETIME YEAR TO SECOND,
  USER_NO        VARCHAR(200) DEFAULT NULL,
  COMPANY_NO     VARCHAR(200) DEFAULT NULL,
  RESULT         VARCHAR(200),
  TYPE           VARCHAR(10)
)lock mode row;
DROP SEQUENCE SEQ_SMS;
CREATE SEQUENCE SEQ_SMS;

DROP TABLE SMS_EMOTICON;
CREATE TABLE SMS_EMOTICON
(
  SEQ_NO         NUMERIC NOT NULL PRIMARY KEY,
  TITLE          VARCHAR(50),
  CONTENT        LVARCHAR(4000),
  REG_DT         VARCHAR(8),
  FLAG_NO        NUMERIC NOT NULL,
  CNT            NUMERIC DEFAULT 0
)lock mode row;
DROP SEQUENCE SEQ_SMS_EMOTICON;
CREATE SEQUENCE SEQ_SMS_EMOTICON;

DROP TABLE SMS_EMOTI_FLAG;
CREATE TABLE SMS_EMOTI_FLAG
(
  FLAG_NO        NUMERIC NOT NULL PRIMARY KEY,
  FLAG           VARCHAR(100)
)lock mode row;
DROP SEQUENCE SEQ_SMS_EMOTI_FLAG;
CREATE SEQUENCE SEQ_SMS_EMOTI_FLAG;

DROP TABLE SMS_REQUEST;
CREATE TABLE SMS_REQUEST
(
  SMS_REQUEST_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  SMS_REQUEST_DATE DATETIME YEAR TO SECOND,
  SMS_REQUEST_SEND_DATE DATETIME YEAR TO SECOND,
  SMS_REQUEST_TYPE CHAR(1) NOT NULL,
  SMS_REQUEST_SEND_HP VARCHAR(20) NOT NULL,
  SMS_REQUEST_RECEIVE_HP VARCHAR(20) NOT NULL,
  SMS_REQUEST_MESSAGE LVARCHAR(4000) NOT NULL
)lock mode row;
DROP SEQUENCE SEQ_SMS_REQUEST;
CREATE SEQUENCE SEQ_SMS_REQUEST;

DROP TABLE SMS_RESULT;
CREATE TABLE SMS_RESULT
(
  SERIALNO       VARCHAR(15) NOT NULL,
  DESTCALLNO     VARCHAR(16) DEFAULT NULL,
  CALLBACKNO     VARCHAR(16) DEFAULT NULL,
  TYPE           CHAR(1) DEFAULT NULL,
  DATA           VARCHAR(200) DEFAULT NULL,
  JEOBSU_TIME    DATETIME YEAR TO SECOND,
  YEYAK_TIME     DATETIME YEAR TO SECOND,
  START_TIME     DATETIME YEAR TO SECOND,
  END_TIME       DATETIME YEAR TO SECOND,
  RESULT         CHAR(2) DEFAULT NULL,
  RESERVED       VARCHAR(30) DEFAULT NULL,
  SUBJECT        VARCHAR(20) DEFAULT NULL,
  USER_NO        VARCHAR(100) DEFAULT NULL,
  COMPANY_NO     VARCHAR(50) DEFAULT NULL,
  JEOBSU_NO      NUMERIC(10) DEFAULT NULL,
  JEOBSU_SUB_NO  NUMERIC(10) DEFAULT NULL,
  PRIMARY KEY (SERIALNO) CONSTRAINT PK_SMS_RESULT
)lock mode row;

DROP TABLE SMS_RESULT_SYSTEM;
CREATE TABLE SMS_RESULT_SYSTEM
(
  SMS_RESULT_SYSTEM_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  SMS_RESULT_SYSTEM_SEND_DATE DATETIME YEAR TO SECOND NOT NULL,
  SMS_RESULT_SYSTEM_TYPE CHAR(1) NOT NULL,
  SMS_RESULT_SYSTEM_SEND_COUNT NUMERIC(5) NOT NULL,
  SMS_RESULT_SYSTEM_CODE CHAR(1) NOT NULL
)lock mode row;
DROP SEQUENCE SEQ_SMS_RESULT_SYSTEM;
CREATE SEQUENCE SEQ_SMS_RESULT_SYSTEM;

DROP TABLE SYSTEM_INFO;
CREATE TABLE SYSTEM_INFO (
  SYSTEM_INFO_IDX VARCHAR(100) NOT NULL,
  SYSTEM_INFO_VALUE LVARCHAR(5000)
)lock mode row;

DROP TABLE USERS_DELETE;
CREATE TABLE USERS_DELETE
(
  USERS_DELETE_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_DELETE_ID VARCHAR(100),
  USERS_DELETE_NAME VARCHAR(200),
  USERS_DELETE_PASSWD VARCHAR(50),
  USERS_DELETE_JUMIN1 VARCHAR(6),
  USERS_DELETE_JUMIN2 VARCHAR(7),
  USERS_DELETE_DEPARTMENT VARCHAR(100),
  USERS_DELETE_LICENCENUM VARCHAR(200)
)lock mode row;
DROP SEQUENCE SEQ_USERS_DELETE;
CREATE SEQUENCE SEQ_USERS_DELETE;

DROP TABLE USERS_MASTER;
CREATE TABLE USERS_MASTER
(
  USERS_IDX      VARCHAR(200) NOT NULL,
  USERS_ID       VARCHAR(100) NOT NULL,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_PASSWD   VARCHAR(200) NOT NULL,
  USERS_NAME     VARCHAR(20) NOT NULL,
  USERS_ENGNAME  VARCHAR(50),
  PRIMARY KEY (USERS_IDX) CONSTRAINT PK_USERS_MASTER
)lock mode row;
CREATE UNIQUE INDEX IDX_USERS_MASTER_ID
   ON USERS_MASTER(USERS_ID);

DROP TABLE USERS_DETAIL;
CREATE TABLE USERS_DETAIL
(
  USERS_IDX      VARCHAR(200) NOT NULL,
  USERS_HOMEDIR  VARCHAR(100) NOT NULL,
  USERS_PERMIT   CHAR(1) NOT NULL,
  USERS_AUTH     CHAR(1) NOT NULL,
  USERS_NICKNAME VARCHAR(40),
  USERS_JUMIN1   VARCHAR(6),
  USERS_JUMIN2   VARCHAR(7),
  USERS_SEX      CHAR(1),
  USERS_BIRTH    VARCHAR(10),
  USERS_ISSOLAR  CHAR(1),
  USERS_CELLNO   VARCHAR(30),
  USERS_FAXNO    VARCHAR(30),
  USERS_TELNO    VARCHAR(30),
  USERS_ZIPCODE  VARCHAR(10),
  USERS_ADDRESS1 VARCHAR(100),
  USERS_ADDRESS2 VARCHAR(100),
  USERS_JOBCODE  CHAR(4),
  USERS_COMPNAME VARCHAR(100),
  USERS_DEPARTMENT VARCHAR(100),
  USERS_PREVEMAIL VARCHAR(50),
  USERS_SCHOOLING CHAR(4),
  USERS_INTEREST CHAR(4),
  USERS_LICENCENUM VARCHAR(200),
  USERS_ISOPEN   VARCHAR(50),
  USERS_JOINDATE DATETIME YEAR TO SECOND,
  USERS_EXPIREDDATE DATETIME YEAR TO SECOND,
  USERS_LOGCOUNT NUMERIC(10),
  USERS_LASTHOST VARCHAR(40),
  USERS_MAX_VOLUME NUMERIC(20),
  USERS_CUR_VOLUME NUMERIC(20),
  USERS_LASTDATE DATETIME YEAR TO SECOND,
  USERS_SIGNATURE CHAR(1),
  USERS_SIGNATURESTMT LVARCHAR(4000),
  USERS_AUTORE   CHAR(1),
  USERS_AUTORESTMT LVARCHAR(4000),
  USERS_USENAME  CHAR(1),
  USERS_SENDBOX  CHAR(1),
  USERS_DELBOX   CHAR(1),
  USERS_AUTO_DEL CHAR(1),
  USERS_LISTNUM  NUMERIC(3),
  USERS_ISVOTE   CHAR(1),
  USERS_ABSENT   CHAR(1),
  USERS_ABSENT_SDATE DATETIME YEAR TO SECOND,
  USERS_ABSENT_EDATE DATETIME YEAR TO SECOND,
  USERS_ABSENT_RESTMT LVARCHAR(4000),
  USERS_OPT_FWD  CHAR(1),
  USERS_OPT_FWD_SAVE CHAR(1),
  USERS_FWD_LIST LVARCHAR(2000),
  USERS_READDR   LVARCHAR(2000),
  USERS_SPAM_LEVEL CHAR(1),
  USERS_DEL_WASTE NUMERIC(2),
  USERS_DEL_SPAM NUMERIC(2),
  USERS_LANG     VARCHAR(10),
  USERS_MAIL_ALARM NUMERIC(3),
  USERS_ALARM_SOUND NUMERIC(2),
  USERS_INDEX_PAGE CHAR(1),
  USERS_RECEIVE_INFOMAIL CHAR(1),
  USERS_MAIL_VIEW NUMERIC(1),
  USERS_MAIL_INJURE CHAR(1),
  USERS_ORGANIZE_IDX NUMERIC(9),
  USERS_AUTHORITY_IDX NUMERIC(9),
  USERS_SMS_QUOTA NUMERIC(9),
  USERS_MAIL_QUOTA NUMERIC(10) DEFAULT 0  NOT NULL,
  USERS_MEMO     LVARCHAR(4000),
  USERS_MSG_YN   CHAR(1),
  USERS_MENTO_YN CHAR(1),
  USERS_USETAG   CHAR(1) DEFAULT 'Y',
  USERS_USE_MAIL_PREVIEW CHAR(1) DEFAULT 'Y',
  MAX_BIG_UPLOAD_SIZE NUMERIC(15) DEFAULT 0
  PRIMARY KEY (USERS_IDX) CONSTRAINT PK_USERS_DETAIL
)lock mode row;

DROP TABLE USERS_PAUSE;
CREATE TABLE USERS_PAUSE
(
  USERS_PAUSE_IDX NUMERIC(10) NOT NULL,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_PAUSE_ID VARCHAR(100),
  USERS_PAUSE_NAME VARCHAR(200),
  USERS_PAUSE_PASSWD VARCHAR(50),
  USERS_PAUSE_JUMIN1 VARCHAR(6),
  USERS_PAUSE_JUMIN2 VARCHAR(7),
  USERS_PAUSE_DEPARTMENT VARCHAR(100),
  USERS_PAUSE_LICENCENUM VARCHAR(200),
  PRIMARY KEY (USERS_PAUSE_IDX) CONSTRAINT PK_USERS_PAUSE
)lock mode row;

DROP TABLE USERS_RECENT_ADDRESS;
CREATE TABLE USERS_RECENT_ADDRESS
(
  RECENT_ADDRESS_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200) NOT NULL,
  ORD_IDX        NUMERIC,
  ADDRESS_NAME   VARCHAR(200),
  ADDRESS_EMAIL  VARCHAR(200) NOT NULL,
  USING_DT       DATETIME YEAR TO SECOND
)lock mode row;
DROP SEQUENCE SEQ_USERS_RECENT_ADDRESS;
CREATE SEQUENCE SEQ_USERS_RECENT_ADDRESS;
   
DROP TABLE USERS_REGIST;
CREATE TABLE USERS_REGIST
(
  USERS_REGIST_IDX NUMERIC NOT NULL PRIMARY KEY,
  DOMAIN         VARCHAR(100) NOT NULL,
  USERS_REGIST_ID VARCHAR(100),
  USERS_REGIST_NAME VARCHAR(200),
  USERS_REGIST_PASSWD VARCHAR(50),
  USERS_REGIST_JUMIN1 VARCHAR(6),
  USERS_REGIST_JUMIN2 VARCHAR(7),
  USERS_REGIST_DEPARTMENT VARCHAR(100),
  USERS_REGIST_LICENCENUM VARCHAR(200)
)lock mode row;
DROP SEQUENCE SEQ_USERS_REGIST;
CREATE SEQUENCE SEQ_USERS_REGIST;


DROP TABLE USER_GROUP;
CREATE TABLE USER_GROUP
(
  USER_GROUP_IDX NUMERIC NOT NULL PRIMARY KEY,
  P_USER_GROUP_IDX NUMERIC(9) NOT NULL,
  USER_GROUP_NAME VARCHAR(200),
  USER_GROUP_SORT_NO NUMERIC,
  DOMAIN         VARCHAR(100),
  USER_GROUP_DEFAULT NCHAR(4),
  USER_GROUP_FUNCTION VARCHAR(20),
  USER_GROUP_VOLUME NCHAR(36),
  USER_GROUP_MAIL NCHAR(4),
  USER_GROUP_SCHEDULE NUMERIC(1),
  USER_GROUP_STRUCTURE NUMERIC(1),
  USER_GROUP_SMS_QUOTA NUMERIC NOT NULL,
  USER_GROUP_ADDRESS NUMERIC(1)
)lock mode row;
DROP SEQUENCE SEQ_USER_GROUP;
CREATE SEQUENCE SEQ_USER_GROUP;

DROP TABLE USER_GROUP_LIST;
CREATE TABLE USER_GROUP_LIST
(
  USER_GROUP_LIST_IDX NUMERIC NOT NULL PRIMARY KEY,
  USERS_IDX      VARCHAR(200),
  USER_GROUP_SORT_NO NUMERIC,
  DOMAIN         VARCHAR(100),
  USER_GROUP_IDX NUMERIC(9) NOT NULL,
  DUTY           VARCHAR(200)
)lock mode row;
DROP SEQUENCE SEQ_USER_GROUP_LIST;
CREATE SEQUENCE SEQ_USER_GROUP_LIST;

DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE
(
  ZIPCODE_CD     VARCHAR(10) NOT NULL,
  ZIPCODE_ADDR1  VARCHAR(20),
  ZIPCODE_ADDR2  VARCHAR(20),
  ZIPCODE_ADDR3  VARCHAR(50),
  ZIPCODE_ADDR4  VARCHAR(50),
  ZIPCODE_CHANGE VARCHAR(20)
);

DROP TABLE M_TAG_BASE;   
CREATE TABLE M_TAG_BASE
(
    TAG_TYPE       NUMERIC(3) NOT NULL,
    TAG_NAME       VARCHAR(200),
    TAG_IMG_NAME   VARCHAR(100) NOT NULL,
    TAG_ORD        NUMERIC(3)
);


/*note*/
DROP TABLE NOTE_RECONF CASCADE CONSTRAINTS;

DROP TABLE REL_NOTE_ATTACHE CASCADE CONSTRAINTS;

DROP TABLE NOTE_ATTACHE CASCADE CONSTRAINTS;

DROP TABLE NOTE_nonghyupcom CASCADE CONSTRAINTS;

CREATE TABLE NOTE_ATTACHE
(
	NOTE_ATTACHE_IDX  NUMBER  NOT NULL ,
	NOTE_ATTACHE_LOCATION  VARCHAR2(200) NOT  NULL,
	NOTE_ATTACHE_LOGICAL_NM  VARCHAR2(100)  NOT NULL ,
	NOTE_ATTACHE_PHYSICAL_NM  VARCHAR2(100)  NOT NULL ,
	NOTE_ATTACHE_SIZE  NUMBER  NULL
);

ALTER TABLE NOTE_ATTACHE
	ADD  PRIMARY KEY (NOTE_ATTACHE_IDX);


CREATE TABLE NOTE_nonghyupcom
(
	NOTE_IDX  NUMBER  NOT NULL ,
	USERS_IDX  VARCHAR2(200)  NOT NULL,
	USERS_ID  VARCHAR2(200)  NOT NULL ,
	DOMAIN  VARCHAR2(200)  NOT NULL ,
	NOTE_BOX_TYPE  NUMBER(1)  NOT NULL ,
	NOTE_SAVE_YN  CHAR(1)  DEFAULT 'N' NOT NULL ,
	NOTE_FROM  VARCHAR2(2000)  NULL ,
	NOTE_TO  VARCHAR2(2000)  NULL ,
	NOTE_CONTENT  NCLOB  NULL ,
	NOTE_TIME  DATE  NULL ,
	REF_NOTE_IDX  NUMBER  NULL,
	NOTE_ISREAD CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE NOTE_nonghyupcom
	ADD  PRIMARY KEY (NOTE_IDX);

CREATE TABLE NOTE_RECONF
(
	NOTE_RECONF_IDX  NUMBER  NOT NULL,
	USERS_IDX  VARCHAR2(200)  NOT NULL ,
	NOTE_IDX  NUMBER  NOT NULL ,
	NOTE_RECONF_TO  VARCHAR2(200)  NULL ,
	NOTE_RECONF_TO_ORI  VARCHAR2(200)  NULL ,
	NOTE_SEND_TIME  DATE  NULL ,
	NOTE_READ_TIME  DATE  NULL ,
	NOTE_SEND_IDX  NUMBER  NULL ,
	NOTE_RECONF_STATE  NUMBER(1)  NULL
);

ALTER TABLE NOTE_RECONF
	ADD  PRIMARY KEY (NOTE_RECONF_IDX);


CREATE TABLE REL_NOTE_ATTACHE
(
	NOTE_IDX  NUMBER  NULL ,
	NOTE_ATTACHE_IDX  NUMBER  NULL 
);


CREATE INDEX IDX_REL_NOTE_ATTACHE1 ON REL_NOTE_ATTACHE
(
	NOTE_IDX  ASC
);


CREATE INDEX IDX_REL_NOTE_ATTACHE2 ON REL_NOTE_ATTACHE
(
	NOTE_ATTACHE_IDX  ASC
);

DROP SEQUENCE SEQ_NOTE_nonghyupcom;
DROP SEQUENCE SEQ_NOTE_ATTACHE;
DROP SEQUENCE SEQ_NOTE_RECONF;

CREATE SEQUENCE SEQ_NOTE_nonghyupcom;
CREATE SEQUENCE SEQ_NOTE_ATTACHE;
CREATE SEQUENCE SEQ_NOTE_RECONF;
/*note*/



CREATE TABLE MANAGER_GRANTIP
(
GRANT_IP_IDX NUMBER(2) NOT NULL ,
GRANT_IP VARCHAR2(15) NOT NULL,
USERS_IDX VARCHAR2(200),
INSERT_DATE DATE,
UPDATE_DATE DATE
);

ALTER TABLE MANAGER_GRANTIP ADD  ( PRIMARY KEY (GRANT_IP_IDX) USING INDEX TABLESPACE KP2_INDX) ;
CREATE SEQUENCE SEQ_GRANT_IP_IDX;